### ISSUE TITLE
Error: No Directive annotation found on [object Object]

### ISSUE THREAD

**Issue by sap9433** [angular/universal-starter#101]
using Angular universal `"angular2-universal": "~0.101.8",` , with `"@angular/core": "2.0.0-rc.1",` . Server starts up fine but whenever I hit `localhost:9876` server fails with following error

`Error: No Directive annotation found on [object Object]
    at new BaseException (/home/saptarshichatterjee/Desktop/server-side-rendering/node_modules/@angular/compiler/src/facade/exceptions.js:17:23)
    at DirectiveResolver.resolve (/home/saptarshichatterjee/Desktop/server-side-rendering/node_modules/@angular/compiler/src/directive_resolver.js:31:15)
    at CompileMetadataResolver.getDirectiveMetadata (/home/saptarshichatterjee/Desktop/server-side-rendering/node_modules/@angular/compiler/src/metadata_resolver.js:55:51)
    at RuntimeCompiler.resolveComponent (/home/saptarshichatterjee/Desktop/server-side-rendering/node_modules/@angular/compiler/src/runtime_compiler.js:34:47)
    at /home/saptarshichatterjee/Desktop/server-side-rendering/node_modules/@angular/core/src/application_ref.js:99:37
    at /home/saptarshichatterjee/Desktop/server-side-rendering/node_modules/@angular/core/src/application_ref.js:292:26
    at ZoneDelegate.invoke (/home/saptarshichatterjee/Desktop/server-side-rendering/node_modules/zone.js/dist/zone-node.js:281:29)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (/home/saptarshichatterjee/Desktop/server-side-rendering/node_modules/@angular/core/src/zone/ng_zone_impl.js:45:41)
    at ZoneDelegate.invoke (/home/saptarshichatterjee/Desktop/server-side-rendering/node_modules/zone.js/dist/zone-node.js:280:35)
    at Zone.run (/home/saptarshichatterjee/Desktop/server-side-rendering/node_modules/zone.js/dist/zone-node.js:174:44)
`

Here's the code base - https://github.com/sap9433/server-side-rendering

**Comment by MarkPieszak** [comment]
Can you take a look at this issue? It looks like it is caused by potentially colliding versions of Angular? (I'm not positive, haven't seen this one myself before)

http://stackoverflow.com/questions/35971299/angular2-exception-no-directive-annotation-found-on-alert

**Comment by sap9433** [comment]
I bumped onto that Stackoverflow thread before , but I'm not using module `ng2-bootstrap`, I', using exactly same dependencies mentioned in `https://github.com/angular/universal-starter`. Here is what my package.json looks like.

```{
  "name": "Angular2-starter-kit",
  "version": "1.0.0",
  "scripts": {
    "start": "webpack && node ./dist/server.js",
    "typings": "typings",
    "postinstall": "typings install"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/platform-server": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "angular2-universal": "~0.101.8",
    "body-parser": "~1.15.1",
    "preboot": "^2.1.2",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.6",
    "webpack-dev-middleware": "^1.6.1",
    "json-loader": "~0.5.4"
  },
  "devDependencies": {
    "express": "^4.13.4",
    "express-http-proxy": "^0.6.0",
    "ts-loader": "^0.8.1",
    "typescript": "^1.8.2",
    "typings": "^0.7.9",
    "webpack": "^1.12.14",
    "webpack-merge": "^0.14.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/sap9433/server-side-rendering"
  }
}
```

**Comment by MarkPieszak** [comment]
Any idea @gdi2290 ? Looked at the repo didn't look like anything stuck out to me

**Comment by gdi2290** [comment]
@sap9433 here's your fix https://github.com/sap9433/server-side-rendering/pull/1 the problem was realizing that there isn't deconstruction in es5
