### ISSUE TITLE
Error: file table overflow 

### ISSUE THREAD

**Issue by kuldeepkeshwar** [angular/universal-starter#104]
on using `templateUrl` in place of inline template , I'm getting below error.

[nodemon] starting `node dist/server/bundle.js`
Listening on: http://localhost:3000
EXCEPTION: Failed to load app.component.html
ngOnInit Error: Failed to load app.component.html
Async Error: [TypeError: Cannot read property 'map' of undefined]
Rendering Document Error: [TypeError: Cannot read property '0' of undefined]
Error: ENFILE: file table overflow, uv_cwd
    at Error (native)
    at posix.resolve (path.js:424:50)
    at View.lookup (/Users/kuldeepkeshwar/ui_workspace/universal-starter/node_modules/express/lib/view.js:105:15)
    at new View (/Users/kuldeepkeshwar/ui_workspace/universal-starter/node_modules/express/lib/view.js:85:20)
    at EventEmitter.render (/Users/kuldeepkeshwar/ui_workspace/universal-starter/node_modules/express/lib/application.js:569:12)
    at ServerResponse.render (/Users/kuldeepkeshwar/ui_workspace/universal-starter/node_modules/express/lib/response.js:961:7)
    at ngApp (/Users/kuldeepkeshwar/ui_workspace/universal-starter/dist/server/bundle.js:78:10)
    at Layer.handle [as handle_request] (/Users/kuldeepkeshwar/ui_workspace/universal-starter/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/kuldeepkeshwar/ui_workspace/universal-starter/node_modules/express/lib/router/index.js:312:13)
    at /Users/kuldeepkeshwar/ui_workspace/universal-starter/node_modules/express/lib/router/index.js:280:7
EXCEPTION: Failed to load app.component.html
ngOnInit Error: Failed to load app.component.html
Async Error: [TypeError: Cannot read property 'map' of undefined]

**Comment by MarkPieszak** [comment]
You cannot use external `html` templates with Universal just yet.
This is already tracked via issue: https://github.com/angular/universal/issues/294 and can be closed out.

**Comment by kuldeepkeshwar** [comment]
what about styleUrls ?

**Comment by MarkPieszak** [comment]
I don't think either work yet, they're both in the pipeline for the initial 1.0 release (I believe) though. I believe with webpack it's possible to use `require()` to be able to use externals (since internally it just injects the html / css). But that's just a temporary work-around.

**Comment by egaspro** [comment]
Using webpack alternative for component-relative paths worked for me: 
https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html#!#webpack ;
As for styles, i could not separate them just yet: you would need something like isomorphic-style-loader instead of style-loader for your webpack to build server bundle and in my case css-loader created a reference with an url server side could not resolve, but that may be due to my different folder structure (https://github.com/angular/universal-starter/issues/105)
