### ISSUE TITLE
Issue in parse5 library

### ISSUE THREAD

**Issue by scrapcupcake** [angular/universal-starter#121]
See https://github.com/angular/universal-starter/issues/54

I am getting the same basic error in the app I am writing, a CMS I am writing to sharpen my skills and host the website for the homeless encampment I am part of. I have uploaded the project here:
https://github.com/scrapcupcake/dcms

My trace looks as follows. I get this from visiting the index of the site.
```
EXCEPTION: TypeError: Cannot read property 'length' of null
STACKTRACE:
TypeError: Cannot read property 'length' of null
    at Preprocessor.write (C:\Users\Scrapcupcake\Desktop\dcms\node_modules\@angular\platform-server\node_modules\parse5\lib\tokenization\preprocessor.js:50:33)
    at new module.exports (C:\Users\Scrapcupcake\Desktop\dcms\node_modules\@angular\platform-server\node_modules\parse5\lib\tokenization\preprocessor.js:29:10)
    at new module.exports (C:\Users\Scrapcupcake\Desktop\dcms\node_modules\@angular\platform-server\node_modules\parse5\lib\tokenization\tokenizer.js:145:25)
    at Parser._reset (C:\Users\Scrapcupcake\Desktop\dcms\node_modules\@angular\platform-server\node_modules\parse5\lib\tree_construction\parser.js:387:22)
    at Parser.parseFragment (C:\Users\Scrapcupcake\Desktop\dcms\node_modules\@angular\platform-server\node_modules\parse5\lib\tree_construction\parser.js:366:10)
    at Parse5DomAdapter.setInnerHTML (C:\Users\Scrapcupcake\Desktop\dcms\node_modules\@angular\platform-server\src\parse5_adapter.js:259:30)
    at Parse5DomAdapter.setProperty (C:\Users\Scrapcupcake\Desktop\dcms\node_modules\@angular\platform-server\src\parse5_adapter.js:54:18)
    at NodeDomRenderer.DomRenderer.setElementProperty (C:\Users\Scrapcupcake\Desktop\dcms\node_modules\@angular\platform-browser\src\dom\dom_renderer.js:167:32)
    at NodeDomRenderer.setElementProperty (C:\Users\Scrapcupcake\Desktop\dcms\node_modules\angular2-universal\dist\node\platform\dom\node_dom_renderer.js:228:59)
    at AppView._View_PageOutlet0.detectChangesInternal (PageOutlet.template.js:26:19)
```

This may be caused by the pattern of use I have here, a subject being changed mid stream, as I am just learning my way through how to use Observables and the like, so please forgive if this is mostly self-inflicted; I saw a similar bug posted, so thought I might have run across a regression, and figured I'd post the code that's making it happen for me.

**Comment by MarkPieszak** [comment]
This isn't an issue with Universal itself, but your configuration isn't set up right (or something is missing in your setup).

I'm not sure, but it could be a lot of things potentially.

I've seen `Cannot read property length of null` when there isn't an array of directives passed to Universal (so it has nothing to parse). Maybe you're passing the App to the server side incorrectly?

I'm not sure which one is your main html file but it could maybe be: `</app>` instead of `<app></app>`.

I would go backwards in your revisions to see when it was last working, that might help to find the issue!

**Comment by scrapcupcake** [comment]
So, I'm fairly sure the issue is with my use of an observable data source, and/or the async pipe, but I'm not sure how to solve it. In particular, there seems to be some confusion (I know I'm a bit lost and confused) as to how best to preload data; I thought the preboot/postboot process handled that for server rendered pages, but I'm not sure how to properly build a data service that will work on client and server; Is using the Http service enough?

**Comment by MarkPieszak** [comment]
Yes you can use the regular `http` service like normal. Once you have the original server rendering and everything setup, you can just business as usual after that!

**Comment by scrapcupcake** [comment]
Unfortunately not what I'm seeing, and I'm not sure why. I'm currently
having server rendering my top level app element but not rendering my child
route elements, but the client does render everything after it fires up the
PageStore and retrieves the data.json again, so both server and client make
the call.

Any suggestions to point me in the right direction are appreciated, thank
you for being polite about my struggles to learn >_<
