### ISSUE TITLE
Cannot find module 'angular2-web-worker/web-worker'

### ISSUE THREAD

**Issue by bhkim526** [angular/universal-starter#133]
I am trying to use 'angular2-web-worker' module ([https://www.npmjs.com/package/angular2-web-worker](https://www.npmjs.com/package/angular2-web-worker)) with Angular Universal but it's throwing below error which doesn't quite make sense to me since it's installed properly and if I switch NG Universal to just serve index.html without prerendering at server-side then it works fine without any exception.
Any help would be appreciated.
```
[nodemon] starting `node dist/server/index.js`
module.js:340
    throw err;
    ^

Error: Cannot find module 'angular2-web-worker/web-worker'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/a08017/dfw-web/dist/server/index.js:3750:19)
    at __webpack_require__ (/Users/a08017/dfw-web/dist/server/index.js:21:30)
    at Object.<anonymous> (/Users/a08017/dfw-web/dist/server/index.js:7356:21)
    at __webpack_require__ (/Users/a08017/dfw-web/dist/server/index.js:21:30)
    at Object.<anonymous> (/Users/a08017/dfw-web/dist/server/index.js:7327:24)
    at __webpack_require__ (/Users/a08017/dfw-web/dist/server/index.js:21:30)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by jeffwhelpley** [comment]
It looks like there are some incompatibilities with this library. Specifically, from what I can see, it works on the client side because you reference a TypeScript file with 'angular2-web-worker/web-worker' and webpack will automatically convert that to JavaScript and include it in your package. However, unless you do a similar packaging for the server side, that won't work. The module author needs to publish in such a way that it is friendly to TypeScript and es5 so you can more easily use it.
