### ISSUE TITLE
Use router in server side

### ISSUE THREAD

**Issue by tamascsaba** [angular/universal-starter#14]
What's wrong?

server.js

```
import {ng2engine, BASE_URL, HTTP_PROVIDERS, SERVER_LOCATION_PROVIDERS} from 'angluar2-universal-preview';
import {provide} from 'angular2/angular2';
import {ROUTER_PROVIDERS, ROUTER_PRIMARY_COMPONENT} from 'angular2/router';

app.use('/', (req, res) => {
  res.render('index', {
    App,
    providers: [
      ROUTER_PROVIDERS,
      HTTP_PROVIDERS,
      SERVER_LOCATION_PROVIDERS,
      provide(BASE_URL, {useValue: '/'}),
      provide(ROUTER_PRIMARY_COMPONENT, { useValue: App }),
    ]
  });
});
```

bootstrap.ts

```
import {bootstrap} from 'angluar2-universal-preview';
import {HTTP_PROVIDERS} from 'angular2/http';
import {ROUTER_PROVIDERS, ROUTER_PRIMARY_COMPONENT, APP_BASE_HREF} from 'angular2/rout
import {App} from './app';


bootstrap(App, [
    ROUTER_PROVIDERS,
    HTTP_PROVIDERS,
    provide(ROUTER_PRIMARY_COMPONENT, { useValue: App }),
    provide(APP_BASE_HREF, { useValue: '/' })
]);
```

Error:
```
TypeError: appRef.registerDisposeListener is not a function
    at routerFactory (/home/dev/universal-starter/node_modules/angular2/router.js:137:12)
    at Injector._instantiate (/home/dev/universal-starter/node_modules/angular2/src/core/di/injector.js:763:27)
    at Injector._instantiateProvider (/home/dev/universal-starter/node_modules/angular2/src/core/di/injector.js:711:25)
    at Injector._new (/home/dev/universal-starter/node_modules/angular2/src/core/di/injector.js:700:21)
    at InjectorDynamicStrategy.getObjByKeyId (/home/dev/universal-starter/node_modules/angular2/src/core/di/injector.js:317:50)
    at Injector._getByKeyDefault (/home/dev/universal-starter/node_modules/angular2/src/core/di/injector.js:896:37)
    at Injector._getByKey (/home/dev/universal-starter/node_modules/angular2/src/core/di/injector.js:842:25)
    at Injector._getByDependency (/home/dev/universal-starter/node_modules/angular2/src/core/di/injector.js:828:25)
    at Injector._instantiate (/home/dev/universal-starter/node_modules/angular2/src/core/di/injector.js:720:36)
    at Injector._instantiateProvider (/home/dev/universal-starter/node_modules/angular2/src/core/di/injector.js:711:25)
```

**Comment by gdi2290** [comment]
the repo needs to be updated to alpha 47

**Comment by tamascsaba** [comment]
thanks the quick answer @gdi2290 :)

**Comment by tamascsaba** [comment]
@gdi2290 any update?

**Comment by graingert** [comment]
@gdi2290 is this updated to the latest version?

**Comment by graingert** [comment]
@gdi2290 @tamascsaba https://github.com/angular/universal-starter/blob/master/package.json#L26

looks like it's updated

**Comment by gdi2290** [comment]
the starter has been updated with the router included in the example
