### ISSUE TITLE
Unable to Start the Server

### ISSUE THREAD

**Issue by alacret** [angular/universal-starter#143]
When I use:

npm start

/vagrant/universal-starter/node_modules/@angular/platform-server/src/facade/collection.js:160
 
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/vagrant/universal-starter/node_modules/@angular/platform-server/src/parse5_adapter.js:15:20)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)

**Comment by manekinekko** [comment]
please check you're using Node 5.

**Comment by alacret** [comment]
Any specific version?

```
vagrant@vagrant:/vagrant/universal-starter$ nvm use 5
Now using node v5.0.0 (npm v3.3.6)
vagrant@vagrant:/vagrant/universal-starter$ node -v
v5.0.0
vagrant@vagrant:/vagrant/universal-starter$ npm start

> universal-starter@2.0.0 prestart /vagrant/universal-starter
> npm run build


> universal-starter@2.0.0 prebuild /vagrant/universal-starter
> rimraf dist


> universal-starter@2.0.0 build /vagrant/universal-starter
> webpack

ts-loader: Using typescript@1.8.10 and /vagrant/universal-starter/tsconfig.json
ts-loader: Using typescript@1.8.10 and /vagrant/universal-starter/tsconfig.json
Hash: 183dd7686231c32bb37b017ad31563219bde8baf
Version: webpack 1.13.1
Child
    Hash: 183dd7686231c32bb37b
    Version: webpack 1.13.1
    Time: 44806ms
       Asset     Size  Chunks             Chunk Names
    index.js  2.66 MB       0  [emitted]  main
        + 455 hidden modules
Child
    Hash: 017ad31563219bde8baf
    Version: webpack 1.13.1
    Time: 36020ms
       Asset     Size  Chunks             Chunk Names
    index.js  13.2 kB       0  [emitted]  main
        + 21 hidden modules

> universal-starter@2.0.0 start /vagrant/universal-starter
> npm run server


> universal-starter@2.0.0 server /vagrant/universal-starter
> nodemon dist/server/index.js

[nodemon] 1.10.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /vagrant/universal-starter/dist/**/* src/index.html
[nodemon] starting `node dist/server/index.js`
/vagrant/universal-starter/node_modules/@angular/platform-server/src/facade/collection.js:160
  
  

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/vagrant/universal-starter/node_modules/@angular/platform-server/src/parse5_adapter.js:15:20)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by ClickSimply** [comment]
Also happening for me.
Windows 10 x64, Node 5.10.1, NPM 3.10.5

It's happening on a fresh clone, no changes made whatsoever.

**Comment by MarkPieszak** [comment]
If you're getting `Unexpected token ILLEGAL` there are probably some illegal characters in your Node code. Try using a different text editor to see them and remove them, maybe they came from copy & pasting code from someplace. You could try putting it into Notepad to see if you can spot them.

**Comment by jeffwhelpley** [comment]
If you work off a clean version of the latest for this repo, you should not get this. I suggest you start there and then apply your changes to the latest starter. Use tslint to find the source of these types of issues.
