### ISSUE TITLE
Node and Express conflicting types

### ISSUE THREAD

**Issue by nchutchind** [angular/universal-starter#162]
I'm using Node 6.0.0 and npm 3.8.6.

The project includes @types/node and @types/express-serve-static-core, which includes its own version of @type/node, resulting in the following error on build:

```
TSError: ⨯ Unable to compile TypeScript
Conflicting library definitions for 'node' found at 'c:/dev/universal-starter-master/node_modules/@types/node/index.d.ts' and 'c:/dev/universal-starter-master/node_modules/@types/express-serve-static-core/node_modules/@types/node/index.d.ts'. Copy the correct file to the 'typings' folder to resolve this conflict. (4090)
    at getOutput (C:\dev\universal-starter-master\node_modules\ts-node\src\index.ts:253:17)
    at C:\dev\universal-starter-master\node_modules\ts-node\src\index.ts:263:16
    at Object.compile (C:\dev\universal-starter-master\node_modules\ts-node\src\index.ts:398:17)
    at Module.m._compile (C:\dev\universal-starter-master\node_modules\ts-node\src\index.ts:299:46)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\dev\universal-starter-master\node_modules\ts-node\src\index.ts:302:14)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
```

**Comment by gdi2290** [comment]
can you try latest? I update some of the types

**Comment by nchutchind** [comment]
Works great! I should have checked and made sure those those libraries were updated when I got the error. Thanks for fixing it.
