### ISSUE TITLE
Deploy build: Error: Failed to lookup view "index" in views directory "src"

### ISSUE THREAD

**Issue by crebuh** [angular/universal-starter#179]
Hey guys, today I tried to build the whole application and deploy it to a aws server. I used **npm run build** to generate the dist folder with the sub-folders server and client.

Then I tried to start the server app with **node dist/server/index.js**, which outputs:

      Listening on: http://localhost:3000

Similar then running the application with **npm start**. In addition I adjusted nginx to serve as proxy so that I can access the localhost of the machine remotley. But then I got this error message in the browser.

     Error: Failed to lookup view "index" in views directory "src"
    at EventEmitter.render (/home/ch/my-app/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/home/ch/my-app/node_modules/express/lib/response.js:960:7)
    at t (/home/ch/my-app/dist/server/index.js:1:25580)
    at Layer.handle [as handle_request] (/home/ch/my-app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ch/my-app/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/ch/my-app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ch/my-app/node_modules/express/lib/router/layer.js:95:5)
    at /home/ch/my-app/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/ch/my-app/node_modules/express/lib/router/index.js:330:12)
    at next (/home/ch/my-app/node_modules/express/lib/router/index.js:271:10)

I guess I'm still missing some config steps. In the meanwhile I justed used npm start to serve webpack-dev-server to make the app accesible remotley. Is there a configuration guide how to serve the build version of the application?

**Comment by jeffwhelpley** [comment]
So, to be clear, this does work for you locally, but it does not work when you try to run it on AWS, right? Please do the following locally:

```
rm -rf node_modules && rm -rf typings
npm i && npm start
```

Then take the entire folder structure and drop it into AWS. Then you should be able to run:

```
nodemon dist/server/index.js
```

Feel free to re-open if that doesn't work.

**Comment by jrojano2** [comment]
I got the same error and in my case the problem was that I uploaded the content of dist instead of the dist folder
