### ISSUE TITLE
No NgModule metadata found for 'MainModule'.

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/universal-starter#221]
Hi @gdi2290 , for the **master** branch, [this line](https://github.com/angular/universal-starter/blob/master/webpack.config.ts#L72) causes the error below now:

> Error: No NgModule metadata found for 'MainModule'.

(Merge to the wrong branch?)

![image](https://cloud.githubusercontent.com/assets/3375461/19789850/125b98c6-9c81-11e6-9317-77fd734cb58a.png)

**Comment by cgarstin** [comment]
Same issue.
Pasted in console output for ease of use
`
[nodemon] starting `node dist/server/index.js`
/Users/cole.garstin/projects/universal-starter-master/node_modules/@angular/compiler/bundles/compiler.umd.js:13726
                  throw new Error("No NgModule metadata found for '" + stringify(type) + "'.");
                  ^

Error: No NgModule metadata found for 'MainModule'.
    at NgModuleResolver.resolve (/Users/cole.garstin/projects/universal-starter-master/node_modules/@angular/compiler/bundles/compiler.umd.js:13726:25)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/cole.garstin/projects/universal-starter-master/node_modules/@angular/compiler/bundles/compiler.umd.js:13966:49)
    at RuntimeCompiler._compileComponents (/Users/cole.garstin/projects/universal-starter-master/node_modules/@angular/compiler/bundles/compiler.umd.js:16721:49)
    at RuntimeCompiler._compileModuleAndComponents (/Users/cole.garstin/projects/universal-starter-master/node_modules/@angular/compiler/bundles/compiler.umd.js:16659:39)
    at RuntimeCompiler.compileModuleAsync (/Users/cole.garstin/projects/universal-starter-master/node_modules/@angular/compiler/bundles/compiler.umd.js:16650:23)
    at NodePlatform.cacheModuleFactory (/Users/cole.garstin/projects/universal-starter-master/node_modules/angular2-platform-node/node-platform.js:84:25)
    at Object.createEngine (/Users/cole.garstin/projects/universal-starter-master/node_modules/angular2-express-engine/index.js:31:28)
    at Object.<anonymous> (/Users/cole.garstin/projects/universal-starter-master/dist/server/index.js:30579:47)
    at Object.<anonymous> (/Users/cole.garstin/projects/universal-starter-master/dist/server/index.js:30621:30)
    at __webpack_require__ (/Users/cole.garstin/projects/universal-starter-master/dist/server/index.js:21:30)
`

**Comment by nicowernli** [comment]
Same issue here since today

**Comment by nicowernli** [comment]
@cgarstin if you remove this lines from webpack.config.ts `externals` will work again. I guess this is a temporary fix

```
'@angular/common',
'@angular/compiler',
'@angular/core',
'@angular/forms',
'@angular/http',
'@angular/platform-browser',
'@angular/platform-browser-dynamic',
'@angular/platform-server',
'@angular/router',
```

**Comment by cgarstin** [comment]
@nicowernli Yes, that works for me. Thanks.
Although I found I could just remove `'@angular/compiler'` and `'@angular/core'`, and still run `npm start` successfully.

**Comment by qdouble** [comment]
That is supposed to be there so we can use AOT with Universal, but is not needed for JIT... hopefully a fix can come soon

**Comment by gdi2290** [comment]
closing since I reverted the commit
