### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by flauc** [angular/universal-starter#265]
When running: 

```ts
npm run build:prod:ngc
```

I get the following error: 

```
TypeError: Cannot read property 'map' of undefined
    at Evaluator.evaluateNode (C:\Users\Detectives\Desktop\Projects\universal-starter\node_modules\@angular\tsc-wrapped\src\evaluator.js:283:54)
    at maybeGetSimpleFunction (C:\Users\Detectives\Desktop\Projects\universal-starter\node_modules\@angular\tsc-wrapped\src\collector.js:46:50)
    at C:\Users\Detectives\Desktop\Projects\universal-starter\node_modules\@angular\tsc-wrapped\src\collector.js:242:41
    at visitEachNode (C:\Users\Detectives\Desktop\Projects\universal-starter\node_modules\typescript\lib\typescript.js:8247:30)
    at Object.forEachChild (C:\Users\Detectives\Desktop\Projects\universal-starter\node_modules\typescript\lib\typescript.js:8407:24)
    at MetadataCollector.getMetadata (C:\Users\Detectives\Desktop\Projects\universal-starter\node_modules\@angular\tsc-wrapped\src\collector.js:204:12)
    at ReflectorHost.getMetadataFor (C:\Users\Detectives\Desktop\Projects\universal-starter\node_modules\@angular\compiler-cli\src\reflector_host.js:228:43)
    at StaticReflector.getModuleMetadata (C:\Users\Detectives\Desktop\Projects\universal-starter\node_modules\@angular\compiler-cli\src\static_reflector.js:490:40)
    at C:\Users\Detectives\Desktop\Projects\universal-starter\node_modules\@angular\compiler-cli\src\codegen.js:122:46
    at Array.forEach (native)
Compilation failed
```

I'm not even sure where to start debugging. Any help is greatly appreciated 👍 

Running the app with out AoT works fine.

**Comment by flauc** [comment]
Meh this was not an angular universal issue sorry guys.
