### ISSUE TITLE
moduleFactory.create is not a function

### ISSUE THREAD

**Issue by flauc** [angular/universal-starter#268]
Started getting this error today: 

```
TypeError: moduleFactory.create is not a function
    at C:\Users\Detectives\Desktop\Projects\universal-starter\dist\server\index.js:23797:43
    at ZoneDelegate.invoke (C:\Users\Detectives\Desktop\Projects\universal-starter\node_modules\zone.js\dist\zone-node.js:232:26)
    at Object.onInvoke (C:\Users\Detectives\Desktop\Projects\universal-starter\dist\server\index.js:26113:37)
    at ZoneDelegate.invoke (C:\Users\Detectives\Desktop\Projects\universal-starter\node_modules\zone.js\dist\zone-node.js:231:32)
    at Zone.run (C:\Users\Detectives\Desktop\Projects\universal-starter\node_modules\zone.js\dist\zone-node.js:114:43)
    at NgZone.run (C:\Users\Detectives\Desktop\Projects\universal-starter\dist\server\index.js:26003:62)
    at PlatformRef_._bootstrapModuleFactoryWithZone (C:\Users\Detectives\Desktop\Projects\universal-starter\dist\server\index.js:23795:23)
    at PlatformRef_.bootstrapModuleFactory (C:\Users\Detectives\Desktop\Projects\universal-starter\dist\server\index.js:23783:21)
    at NodePlatform.bootstrapModuleFactory (C:\Users\Detectives\Desktop\Projects\universal-starter\dist\server\index.js:56373:33)
    at NodePlatform.serializeModuleFactory (C:\Users\Detectives\Desktop\Projects\universal-starter\dist\server\index.js:56051:21)
```

Nothing changed in the app since yesterday. I just reinstalled node_modules i think this has something to do with one of the dependencies getting updated.

**Comment by MarkPieszak** [comment]
Can you try wiping the project out and trying with the latest? It might of been a commit somewhere that caused this issue that was fixed after. Let us know!

**Comment by gdi2290** [comment]
make sure you compile ngc
npm run build:prod:ngc

**Comment by flauc** [comment]
npm run build:prod:ngc runs with no problems and the app works. The problem is with `npm start` it runs but when navigating to localhost i get the error.

**Comment by gdi2290** [comment]
the problem is that npm start runs the jit version of angular but for some reason the server, for your local copy of the repo, is trying to bootstrap the AoT ng-module

**Comment by gdi2290** [comment]
can you pull latest changes. You might have downloaded a copy where I was still pushing code

**Comment by flauc** [comment]
I will try thank you for the helping 👍

**Comment by flauc** [comment]
Looks like pulling the newest version solves the bug. I'm still not quite sure what caused it. I think it might have been a bug in some dependence.
