### ISSUE TITLE
Unmet peer dependency for @angular/compiler-cli and @angular/core

### ISSUE THREAD

**Issue by ndamnjanovic** [angular/universal-starter#307]
I'm getting following errors when running `npm install` (with latest code from master).
Any solutions, am I missing something?

    npm WARN @ngtools/webpack@1.1.9 requires a peer of @angular/compiler-cli@2.2.3 but none was installed.
    npm WARN @ngtools/webpack@1.1.9 requires a peer of @angular/core@2.2.3 but none was installed.

Is this something I can ignore?

Thanks!

**Comment by matthiasg** [comment]
it also is complaining about

```
Error: Cannot find module 'webpack-sources'
```

when calling `npm run build:prod:ngc` which means `npm i webpack-sources` is required

rest of message
```
  ...
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\Development\Test\angular2\universal-starter\node_modules\v8-lazy-parse-webpack-plugin\V8LazyParsedFunctionModuleTemplatePlugin.js:5:46)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by matthiasg** [comment]
It is also missing `npm i es6-shim es6-promise ie-shim`

**Comment by rosdi** [comment]
I am getting the same warnings:
```
npm WARN @ngtools/webpack@1.1.9 requires a peer of @angular/compiler-cli@2.2.3 but none was installed.
npm WARN @ngtools/webpack@1.1.9 requires a peer of @angular/core@2.2.3 but none was installed.
```
This is my `package.json` (mostly the default package.json generated by `ng new`)

```
{
  "name": "ngcli",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "core-js": "^2.4.1",
    "ng2-completer": "^0.4.0",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.24",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "~2.0.3"
  }
}
```

**Comment by MarkPieszak** [comment]
Hmm something must of updated that's causing this chain reaction, I'll try and take a look later today to see what's going on. I'm guessing it's a Dep that ^ takes newer versions we might have to pin one of them for now. @gdi2290 webpack drop some breaking dep changes maybe?

**Comment by Shiroh1ge** [comment]
Has this been worked out? I'm trying to update to 4.0.0-beta3 or at least 2.4.3, has anyone done that successfully? I am too getting these dependency errors

**Comment by rosdi** [comment]
Not errors... 'just' warnings... (at least on my case). My app builds and is working fine though... granted it is just a simple app with no routing, aot, lazy loadings, etc...

**Comment by Shiroh1ge** [comment]
I see, will ignore them for now then! Thanks!
