### ISSUE TITLE
Updated meta tags not rendering on server

### ISSUE THREAD

**Issue by dottodot** [angular/universal-starter#310]
The following updates the meta description on the client but is not rendered on the server and throws an error.

```
import { Component, ChangeDetectionStrategy, ViewEncapsulation } from '@angular/core';

import { ModelService } from '../shared/model/model.service';
import { Meta } from '../../angular2-meta';
@Component({
  changeDetection: ChangeDetectionStrategy.Default,
  encapsulation: ViewEncapsulation.Emulated,
  selector: 'home',
  styleUrls: [ './home.component.css' ],
  templateUrl: './home.component.html'
})
export class HomeComponent {
  data: any = {};
  constructor(public model: ModelService, private _meta: Meta) {

    // we need the data synchronously for the client to set the server response
    // we create another method so we have more control for testing
    this.universalInit();
  }

  universalInit() {
    const desc: HTMLMetaElement = this._meta.updateTag('name=description', {name: 'description', content: 'New description'});
    this.model.get('/data.json').subscribe(data => {
      this.data = data;
    });
  }

}
```

```
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'attribs' of undefined
TypeError: Cannot read property 'attribs' of undefined
    at Parse5DomAdapter.classList (/universal-starter/dist/server/index.js:55997:33)
    at Parse5DomAdapter.addClass (/universal-starter/dist/server/index.js:56004:30)
    at Meta.getTag (/universal-starter/dist/server/index.js:27506:19)
    at Meta.updateTag (/universal-starter/dist/server/index.js:27525:25)
    at HomeComponent.universalInit (/universal-starter/dist/server/index.js:41797:31)
    at new HomeComponent (/universal-starter/dist/server/index.js:41793:14)
    at new Wrapper_HomeComponent (/HomeModule/HomeComponent/wrapper.ngfactory.js:6:18)
    at AppView._View_HomeComponent_Host0.createInternal (/HomeModule/HomeComponent/host.ngfactory.js:15:29)
    at AppView.create (/universal-starter/dist/server/index.js:42651:21)
    at ComponentFactory.create (/universal-starter/dist/server/index.js:27825:36)

```

**Comment by MarkPieszak** [comment]
Are you using the provided angular2-meta service? https://github.com/angular/universal-starter/blob/f9cb6cfae7649849f150f0697feec79b63dde3de/src/angular2-meta.ts

**Comment by inzerceubytovani** [comment]
Look here - https://github.com/angular/universal-starter/issues/287

**Comment by Jamie452** [comment]
I'm having a similar error while trying to implement ng-bootstrap's ngbDropdown - fails with error:

```
ERROR TypeError: Cannot read property 'attribs' of undefined
    at Parse5DomAdapter.classList (/Users/jamiestreet/Work/Frontend/dist/server.js:39550:50)
    at Parse5DomAdapter.removeClass (/Users/jamiestreet/Work/Frontend/dist/server.js:39575:47)
    at EmulatedEncapsulationServerRenderer2.DefaultServerRenderer2.removeClass (/Users/jamiestreet/Work/Frontend/dist/server.js:40461:151)
    at BaseAnimationRenderer.removeClass (/Users/jamiestreet/Work/Frontend/dist/server.js:57615:87)
    at NgbDropdownMenu.applyPlacement (/Users/jamiestreet/Work/Frontend/dist/server.js:50372:24)
    at NgbDropdown.ngOnInit (/Users/jamiestreet/Work/Frontend/dist/server.js:50446:24)
    at checkAndUpdateDirectiveInline (/Users/jamiestreet/Work/Frontend/dist/server.js:11384:19)
    at checkAndUpdateNodeInline (/Users/jamiestreet/Work/Frontend/dist/server.js:12885:17)
    at checkAndUpdateNode (/Users/jamiestreet/Work/Frontend/dist/server.js:12824:16)
    at prodCheckAndUpdateNode (/Users/jamiestreet/Work/Frontend/dist/server.js:13518:5)
```

Is there a solution to this?

**Comment by MarkPieszak** [comment]
@Jamie452 Can you open a new specific issue with what you're doing and how we could try and replicate it? Closing this one out as it's very old and so much has updated since the OP. Thanks!
