### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by kevinlllR** [angular/universal-starter#356]
When I install @ angular / material, I get the following error, and verify that it is this module, because when I remove all the lines corresponding to it the error disappears, I tried to install other versions of the same module but the error persists.
```

Listening on: http://localhost:3000
EXCEPTION: navigator is not defined
ORIGINAL STACKTRACE:
ReferenceError: navigator is not defined
    at new Platform (C:\Users\LANCENTER\Desktop\universal-starter-master\dist\se
rver\index.js:20114:36)
    at NgModuleInjector.get (/MainModule/module.ngfactory.js:254:63)
    at NgModuleInjector.get (/MainModule/module.ngfactory.js:279:122)
    at NgModuleInjector.MainModuleInjector.getInternal (/MainModule/module.ngfac
tory.js:576:60)
    at NgModuleInjector.get (C:\Users\LANCENTER\Desktop\universal-starter-master
\dist\server\index.js:40335:27)
    at ElementInjector.get (C:\Users\LANCENTER\Desktop\universal-starter-master\
dist\server\index.js:59446:48)
    at ElementInjector.get (C:\Users\LANCENTER\Desktop\universal-starter-master\
dist\server\index.js:59446:48)
    at AppView._View_MdSidenav0.createInternal (/MdSidenavModule/MdSidenav/compo
nent.ngfactory.js:17:72)
    at AppView.create (C:\Users\LANCENTER\Desktop\universal-starter-master\dist\
server\index.js:59762:21)
    at AppView._View_AppComponent0.createInternal (/AppModule/AppComponent/compo
nent.ngfactory.js:72:17)
ReferenceError: navigator is not defined
    at new Platform (C:\Users\LANCENTER\Desktop\universal-starter-master\dist\se
rver\index.js:20114:36)
    at NgModuleInjector.get (/MainModule/module.ngfactory.js:254:63)
    at NgModuleInjector.get (/MainModule/module.ngfactory.js:279:122)
    at NgModuleInjector.MainModuleInjector.getInternal (/MainModule/module.ngfac
tory.js:576:60)
    at NgModuleInjector.get (C:\Users\LANCENTER\Desktop\universal-starter-master
\dist\server\index.js:40335:27)
    at ElementInjector.get (C:\Users\LANCENTER\Desktop\universal-starter-master\
dist\server\index.js:59446:48)
    at ElementInjector.get (C:\Users\LANCENTER\Desktop\universal-starter-master\
dist\server\index.js:59446:48)
    at AppView._View_MdSidenav0.createInternal (/MdSidenavModule/MdSidenav/compo
nent.ngfactory.js:17:72)
    at AppView.create (C:\Users\LANCENTER\Desktop\universal-starter-master\dist\
server\index.js:59762:21)
    at AppView._View_AppComponent0.createInternal (/AppModule/AppComponent/compo
nent.ngfactory.js:72:17)
GET / 304 125.003 ms - -
GET /assets/indigo.css 304 67.642 ms - -
GET /main.bundle.js 200 74.563 ms - -

```

**Comment by MarkPieszak** [comment]
Material is not compatible with Universal at the moment, you can see the issue on it here (https://github.com/angular/material2/issues/308).

There are some hacks to potentially get it working (I can't find where someone had posted them at the moment). If you need to get going on your application and can't get the workarounds going, you could disable universal for the time being until they are working together again.

**Comment by gdi2290** [comment]
see correct hacks to get material working
https://github.com/angular/material2/issues/308#issuecomment-275361791

**Comment by ryanstrandt** [comment]
Just so you know - I got the same error when adding in the @angular/service-worker to have a pwa on the client side. Don't know if the same issue exists as with material.

**Comment by chozharajan** [comment]
@kevinlllR are you fixed this  _**"navigator is not defined**_" issue give me some guidelines step by step am also getting the same error and others as well waiting for replay

**Comment by jorgjanke** [comment]
Steps to reproduce:
ng new --style scss --routing true --service-worker www.abc.com

ng generate universal ngu-app-shell
.. add router outlet
ng generate app-shell my-shell --universal=ngu-app-shell --route=app-shell-path

ng build --prod
\Date: 2018-03-07T07:35:39.184Z                                                          
Hash: dc03561d506c82fd921d
Time: 11863ms
chunk {0} polyfills.bf95165a1d5098766b92.bundle.js (polyfills) 59.4 kB [initial] [rendered]
chunk {1} main.9b2081e955efa31363b3.bundle.js (main) 248 kB [initial] [rendered]
chunk {2} styles.ac89bfdd6de82636b768.bundle.css (styles) 0 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]
Date: 2018-03-07T07:35:41.867Z                                                       
Hash: aaa3ef3b2347d8947004
Time: 2605ms
chunk {0} main.81376bad3450b4f4c01e.bundle.js (main) 11.2 kB [entry] [rendered]
chunk {1} styles.ac89bfdd6de82636b768.bundle.css (styles) 0 bytes [entry] [rendered]
ERROR ReferenceError: navigator is not defined
    at ngswCommChannelFactory (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/service-worker/bundles/service-worker.umd.js:480:57)
    at _callFactory (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:10956:20)
    at _createProviderInstance$1 (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:10906:26)
    at resolveNgModuleDep (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:10888:17)
    at _createClass (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:10929:29)
    at _createProviderInstance$1 (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:10903:26)
    at resolveNgModuleDep (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:10888:17)
    at NgModuleRef_.get (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:12125:16)
    at resolveDep (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:12615:45)
    at createClass (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:12477:29)
    at createDirectiveInstance (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:12322:37)
    at createViewNodes (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:13780:53)
    at createRootView (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:13669:5)
    at Object.createProdRootView [as createRootView] (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:14362:12)
    at ComponentFactory_.create (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:11274:46)
    at ComponentFactoryBoundToModule.create (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/core/bundles/core.umd.js:4061:29)
Unhandled Promise rejection: navigator is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: navigator is not defined
    at ngswCommChannelFactory (/Users/jorg/Documents/Universal/www.track4d.com/node_modules/@angular/service-worker/bundles/service-worker.umd.js:480:57)

**Comment by tomschreck** [comment]
I'm getting the exact same issue following Angular University's Angular PWA course

**Comment by raviayadav** [comment]
@tomschreck got any solution for that?
