### ISSUE TITLE
Buffer is not defined AND Parameter 'url' must be a string, not undefined ERROR

### ISSUE THREAD

**Issue by FelipeTaiarol** [angular/universal-starter#368]
I am trying to add angular2-universal to my application and I am using universal-starter as a reference. I was able to get server rendering to work but I get a weird error when the code runs in the browser. 

```javascript
util.js:103Uncaught ReferenceError: Buffer is not defined . 
    at Object.<anonymous> (util.js:103) . 
    at __webpack_require__ (bootstrap efbd556…:19) . 
    at Object.<anonymous> (_stream_readable.js:46) . 
    at Object.<anonymous> (_stream_readable.js:982) . 
    at __webpack_require__ (bootstrap efbd556…:19) . 
    at Object.<anonymous> (readable.js:2) . 
    at __webpack_require__ (bootstrap efbd556…:19) . 
    at Object.<anonymous> (index.js:28) . 
    at __webpack_require__ (bootstrap efbd556…:19) . 
    at Object.<anonymous> (stream.js:3)
```   

If I change webpack.config.ts from . 

```javascript
export var clientConfig = {
  target: 'web',
  entry: './src/client',
  output: {
    path: root('dist/client')
  },
  node: {
    global: true,
    crypto: 'empty',
    __dirname: true,
    __filename: true,
    process: true,
    Buffer: false
  }
};
```
to:  

```javascript
export var clientConfig = {
  target: 'web',
  entry: './src/client',
  output: {
    path: root('dist/client')
  },
  node: {
    global: true,
    crypto: 'empty',
    __dirname: true,
    __filename: true,
    process: true,
    Buffer: true
  }
};
```

this error is gone but then I get a different error:  

```javascript
zone.js:388Unhandled Promise rejection: Parameter 'url' must be a string, not undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:112)
    at urlParse (url.js:106)
    at Object.urlResolve [as resolve] (url.js:439)
    at NodePlatformLocation._setLocationByUrl (node-location.js:167)
    at NodePlatformLocation._updateLocation (node-location.js:164)
    at NodePlatformLocation.pushState (node-location.js:125)
    at new NodePlatformLocation (node-location.js:94)
    at MainModuleInjector.get (/MainModule/module.ngfactory.js:215)
    at MainModuleInjector.get (/MainModule/module.ngfactory.js:229)
    at MainModuleInjector.get (/MainModule/module.ngfactory.js:234) TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (http://localhost:8080/main.bundle.js:53810:11)
    at urlParse (http://localhost:8080/main.bundle.js:53804:5)
    at Object.urlResolve [as resolve] (http://localhost:8080/main.bundle.js:54137:10)
    at NodePlatformLocation._setLocationByUrl (http://localhost:8080/main.bundle.js:67424:42)
    at NodePlatformLocation._updateLocation (http://localhost:8080/main.bundle.js:67421:14)
    at NodePlatformLocation.pushState (http://localhost:8080/main.bundle.js:67382:14)
    at new NodePlatformLocation (http://localhost:8080/main.bundle.js:67351:14)
    at MainModuleInjector.get (/MainModule/module.ngfactory.js:215:77)
    at MainModuleInjector.get (/MainModule/module.ngfactory.js:229:111)
    at MainModuleInjector.get (/MainModule/module.ngfactory.js:234:84)
consoleError @ zone.js:388
_loop_1 @ zone.js:417
drainMicroTaskQueue @ zone.js:421
zone.js:390Error: Uncaught (in promise): TypeError: Parameter 'url' must be a string, not undefined
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:112)
    at urlParse (url.js:106)
    at Object.urlResolve [as resolve] (url.js:439)
    at NodePlatformLocation._setLocationByUrl (node-location.js:167)
    at NodePlatformLocation._updateLocation (node-location.js:164)
    at NodePlatformLocation.pushState (node-location.js:125)
    at new NodePlatformLocation (node-location.js:94)
    at MainModuleInjector.get (/MainModule/module.ngfactory.js:215)
    at MainModuleInjector.get (/MainModule/module.ngfactory.js:229)
    at MainModuleInjector.get (/MainModule/module.ngfactory.js:234)
    at Url.parse (url.js:112)
    at urlParse (url.js:106)
    at Object.urlResolve [as resolve] (url.js:439)
    at NodePlatformLocation._setLocationByUrl (node-location.js:167)
    at NodePlatformLocation._updateLocation (node-location.js:164)
    at NodePlatformLocation.pushState (node-location.js:125)
    at new NodePlatformLocation (node-location.js:94)
    at MainModuleInjector.get (/MainModule/module.ngfactory.js:215)
    at MainModuleInjector.get (/MainModule/module.ngfactory.js:229)
    at MainModuleInjector.get (/MainModule/module.ngfactory.js:234)
    at resolvePromise (zone.js:468)
    at zone.js:505
    at ZoneDelegate.invokeTask (zone.js:265)
    at Zone.runTask (zone.js:154)
    at drainMicroTaskQueue (zone.js:401)
```
any ideas ?

**Comment by FelipeTaiarol** [comment]
never mind, I looked to the code again with fresh eyes and realized I was importing UniversalModule inside app.component among other small mistakes, thanks!

**Comment by MarkPieszak** [comment]
Glad you figured it out!
