### ISSUE TITLE
Error After Upgrading to Angular 2.4.9

### ISSUE THREAD

**Issue by afganhalbana** [angular/universal-starter#382]
Hey guys, could anyone help me with this issue, so basically i need to upgrade my Angular version to the latest in order to get work with angular2-froala-wysiwyg. Unfortunately, ive got caught with this error after upgrading angular version to the latest which is 2.4.9.

Unhandled Promise rejection: Cannot read property 'push' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'push' of undefined
    at http://localhost:3000/main.bundle.js:90130:37
    at Array.forEach (native)
    at new UniversalModule (http://localhost:3000/main.bundle.js:90128:16)
    at MainModuleInjector.createInternal (/MainModule/module.ngfactory.js:531:29)
    at MainModuleInjector.NgModuleInjector.create (http://localhost:3000/main.bundle.js:60778:76)
    at NgModuleFactory.create (http://localhost:3000/main.bundle.js:60746:18)
    at http://localhost:3000/main.bundle.js:41270:61
    at ZoneDelegate.invoke (http://localhost:3000/main.bundle.js:110213:26)
    at Object.onInvoke (http://localhost:3000/main.bundle.js:31011:37)
    at ZoneDelegate.invoke (http://localhost:3000/main.bundle.js:110212:32)
    at Zone.run (http://localhost:3000/main.bundle.js:110084:43)
    at NgZone.run (http://localhost:3000/main.bundle.js:30880:62)
    at PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:3000/main.bundle.js:41268:23)
    at http://localhost:3000/main.bundle.js:41319:59
    at ZoneDelegate.invoke (http://localhost:3000/main.bundle.js:110213:26) TypeError: Cannot read property 'push' of undefined
    at http://localhost:3000/main.bundle.js:90130:37
    at Array.forEach (native)
    at new UniversalModule (http://localhost:3000/main.bundle.js:90128:16)
    at MainModuleInjector.createInternal (/MainModule/module.ngfactory.js:531:29)
    at MainModuleInjector.NgModuleInjector.create (http://localhost:3000/main.bundle.js:60778:76)
    at NgModuleFactory.create (http://localhost:3000/main.bundle.js:60746:18)
    at http://localhost:3000/main.bundle.js:41270:61
    at ZoneDelegate.invoke (http://localhost:3000/main.bundle.js:110213:26)
    at Object.onInvoke (http://localhost:3000/main.bundle.js:31011:37)
    at ZoneDelegate.invoke (http://localhost:3000/main.bundle.js:110212:32)
    at Zone.run (http://localhost:3000/main.bundle.js:110084:43)
    at NgZone.run (http://localhost:3000/main.bundle.js:30880:62)
    at PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:3000/main.bundle.js:41268:23)
    at http://localhost:3000/main.bundle.js:41319:59
    at ZoneDelegate.invoke (http://localhost:3000/main.bundle.js:110213:26)
consoleError @ zone.js:405
zone.js:407Error: Uncaught (in promise): TypeError: Cannot read property 'push' of undefined
TypeError: Cannot read property 'push' of undefined
    at http://localhost:3000/main.bundle.js:90130:37
    at Array.forEach (native)
    at new UniversalModule (http://localhost:3000/main.bundle.js:90128:16)
    at MainModuleInjector.createInternal (/MainModule/module.ngfactory.js:531:29)
    at MainModuleInjector.NgModuleInjector.create (http://localhost:3000/main.bundle.js:60778:76)
    at NgModuleFactory.create (http://localhost:3000/main.bundle.js:60746:18)
    at http://localhost:3000/main.bundle.js:41270:61
    at ZoneDelegate.invoke (http://localhost:3000/main.bundle.js:110213:26)
    at Object.onInvoke (http://localhost:3000/main.bundle.js:31011:37)
    at ZoneDelegate.invoke (http://localhost:3000/main.bundle.js:110212:32)
    at Zone.run (http://localhost:3000/main.bundle.js:110084:43)
    at NgZone.run (http://localhost:3000/main.bundle.js:30880:62)
    at PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:3000/main.bundle.js:41268:23)
    at http://localhost:3000/main.bundle.js:41319:59
    at ZoneDelegate.invoke (http://localhost:3000/main.bundle.js:110213:26)
    at http://localhost:3000/main.bundle.js:90130:37
    at Array.forEach (native)
    at new UniversalModule (http://localhost:3000/main.bundle.js:90128:16)
    at MainModuleInjector.createInternal (/MainModule/module.ngfactory.js:531:29)
    at MainModuleInjector.NgModuleInjector.create (http://localhost:3000/main.bundle.js:60778:76)
    at NgModuleFactory.create (http://localhost:3000/main.bundle.js:60746:18)
    at http://localhost:3000/main.bundle.js:41270:61
    at ZoneDelegate.invoke (http://localhost:3000/main.bundle.js:110213:26)
    at Object.onInvoke (http://localhost:3000/main.bundle.js:31011:37)
    at ZoneDelegate.invoke (http://localhost:3000/main.bundle.js:110212:32)
    at Zone.run (http://localhost:3000/main.bundle.js:110084:43)
    at NgZone.run (http://localhost:3000/main.bundle.js:30880:62)
    at PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:3000/main.bundle.js:41268:23)
    at http://localhost:3000/main.bundle.js:41319:59
    at ZoneDelegate.invoke (http://localhost:3000/main.bundle.js:110213:26)
    at resolvePromise (http://localhost:3000/main.bundle.js:110457:31) [<root>]
    at http://localhost:3000/main.bundle.js:110494:17 [<root>]
    at Zone.runTask (http://localhost:3000/main.bundle.js:110122:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:3000/main.bundle.js:110389:35) [<root>]
consoleError @ zone.js:407
home:1 The resource http://localhost:3000/assets/logo.png was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.

And this is my package.json

"dependencies": {
    "@angular/common": "^2.4.9",
    "@angular/compiler": "^2.4.9",
    "@angular/compiler-cli": "^2.4.9",
    "@angular/core": "^2.4.9",
    "@angular/forms": "^2.4.9",
    "@angular/http": "^2.4.9",
    "@angular/platform-browser": "^2.4.9",
    "@angular/platform-browser-dynamic": "^2.4.9",
    "@angular/platform-server": "^2.4.9",
    "@angular/router": "^3.4.9",
    "@angular/upgrade": "^2.4.9",
    "@angularclass/bootloader": "^1.0.1",
    "@angularclass/idle-preload": "^1.0.4",
    "@ngrx/core": "^1.2.0",
    "@ngrx/db": "^2.0.1",
    "@ngrx/effects": "^2.0.0",
    "@ngrx/router-store": "^1.2.5",
    "@ngrx/store": "^2.2.1",
    "@ngrx/store-devtools": "^3.2.3",
    "@ngrx/store-log-monitor": "^3.0.2",
    "@types/accepts": "^1.3.0",
    "@types/bluebird": "^3.0.37",
    "@types/memory-cache": "^0.0.29",
    "@types/redis": "^0.12.35",
    "@types/request": "^0.0.39",
    "accepts": "^1.3.3",
    "angular2-express-engine": "~2.1.0-rc.1",
    "angular2-froala-wysiwyg": "^2.5.1-1",
    "angular2-platform-node": "~2.1.0-rc.1",
    "angular2-universal": "~2.1.0-rc.1",
    "angular2-universal-polyfills": "~2.1.0-rc.1",
    "autoprefixer": "^6.6.1",
    "bluebird": "^3.4.7",
    "body-parser": "^1.15.2",
    "compression": "^1.6.2",
    "connect-redis": "^3.2.0",
    "express": "^4.14.0",
    "express-interceptor": "^1.2.0",
    "express-session": "^1.15.0",
    "extract-text-webpack-plugin": "2.0.0-rc.2",
    "file-loader": "^0.10.1",
    "font-awesome": "^4.7.0",
    "js.clone": "0.0.3",
    "memory-cache": "^0.1.6",
    "methods": "~1.1.2",
    "morgan": "^1.7.0",
    "ngrx-store-freeze": "^0.1.9",
    "passport": "^0.3.2",
    "path": "^0.12.7",
    "preboot": "~4.5.2",
    "redis": "^2.6.5",
    "request": "^2.79.0",
    "reselect": "^2.5.4",
    "rxjs": "5.0.0-beta.12",
    "url-loader": "^0.5.8",
    "webfontloader": "^1.6.26",
    "zone.js": "0.7.4"
  },
  "devDependencies": {
    "@ngtools/webpack": "~1.1.7",
    "@types/body-parser": "0.0.29",
    "@types/compression": "0.0.29",
    "@types/cookie-parser": "^1.3.29",
    "@types/express": "^4.0.32",
    "@types/express-serve-static-core": "^4.0.33",
    "@types/hammerjs": "^2.0.32",
    "@types/mime": "0.0.28",
    "@types/morgan": "^1.7.32",
    "@types/node": "^6.0.38",
    "@types/serve-static": "^1.7.27",
    "@types/webfontloader": "^1.6.27",
    "angular2-template-loader": "^0.4.0",
    "awesome-typescript-loader": "^2.2.4",
    "cookie-parser": "^1.4.3",
    "css-loader": "^0.26.1",
    "imports-loader": "^0.6.5",
    "json-loader": "^0.5.4",
    "node-sass": "^4.2.0",
    "nodemon": "^1.10.0",
    "postcss-loader": "^1.2.2",
    "raw-loader": "^0.5.1",
    "reflect-metadata": "0.1.8",
    "rimraf": "^2.5.4",
    "sass-loader": "^4.1.1",
    "string-replace-loader": "^1.0.5",
    "style-loader": "^0.13.1",
    "ts-helpers": "^1.1.2",
    "ts-node": "^1.3.0",
    "typescript": "2.0.2",
    "v8-lazy-parse-webpack-plugin": "^0.3.0",
    "webpack": "2.1.0-beta.27",
    "webpack-bundle-analyzer": "1.4.1",
    "webpack-dev-middleware": "^1.8.4",
    "webpack-dev-server": "2.1.0-beta.11",
    "webpack-merge": "~0.16.0"
  }

Im curious what happened with this error, since it got worked with Angular version 2.1.2. Any help would be appreciated , thanks

**Comment by afganhalbana** [comment]
I've fixed this issued by upgrading yarn to the latest version. After see the obvious error message about unmet peer dependency to each angular packages and resolve it, thank God now its working.
