### ISSUE TITLE
HTTP fetch fails: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by bjwyse** [angular/universal-starter#41]
I have added a service using HTTP fetch as described at https://angular.io/docs/ts/latest/guide/server-communication.html#!#fetch-data to my universal app but the request fails on the server side.

I have seen that there is a Node XHR Implementation but I don't know how to use it or if it even works.

Sample code at https://github.com/bjwyse/universal-starter/tree/http_fetch_test will reproduce the error.

```
EXCEPTION: ReferenceError: XMLHttpRequest is not defined in [null]
ORIGINAL EXCEPTION: ReferenceError: XMLHttpRequest is not defined
ORIGINAL STACKTRACE:
ReferenceError: XMLHttpRequest is not defined
    at BrowserXhr.build (c:\Users\bwyse\projects\ng2\universal-starter-bw\node_modules\angular2\src\http\backends\browser_xhr.js:19:60)
    at Observable._subscribe (c:\Users\bwyse\projects\ng2\universal-starter-bw\node_modules\angular2\src\http\backends\xhr_backend.js:32:35)
    at Observable._subscribe (c:\Users\bwyse\projects\ng2\universal-starter-bw\node_modules\rxjs\Observable.js:118:28)
    at Observable._subscribe (c:\Users\bwyse\projects\ng2\universal-starter-bw\node_modules\rxjs\Observable.js:118:28)
    at Observable.subscribe (c:\Users\bwyse\projects\ng2\universal-starter-bw\node_modules\rxjs\Observable.js:74:29)
    at App.getAppPropertiesApi (c:\Users\bwyse\projects\ng2\universal-starter-bw\dist\server\bundle.js:186:15)
    at App.ngOnInit (c:\Users\bwyse\projects\ng2\universal-starter-bw\dist\server\bundle.js:181:15)
    at AbstractChangeDetector.ChangeDetector_HostApp_0.detectChangesInRecordsInternal (viewFactory_HostApp:21:99)
    at AbstractChangeDetector.detectChangesInRecords (c:\Users\bwyse\projects\ng2\universal-starter-bw\node_modules\angular2\src\core\change_detection\abstract_change_detector.js:105:18)
    at AbstractChangeDetector.runDetectChanges (c:\Users\bwyse\projects\ng2\universal-starter-bw\node_modules\angular2\src\core\change_detection\abstract_change_detector.js:82:14)
```

**Comment by manekinekko** [comment]
@bjwyse Could you give some basic steps to reproduce this?

**Comment by bjwyse** [comment]
@manekinekko can you try the http_fetch_test branch at my fork here -> https://github.com/bjwyse/universal-starter.git?

**Comment by manekinekko** [comment]
@bjwyse in order to fix your error about `ReferenceError: XMLHttpRequest is not defined`. See the diff below.

However, we're still having issues with `Http` in the universal core. So XHR calls may not work for the moment. See https://github.com/angular/universal/issues/292

```diff
diff --git a/src/app/app.ts b/src/app/app.ts
index 8f05c6a..d450287 100644
--- a/src/app/app.ts
+++ b/src/app/app.ts
@@ -1,7 +1,5 @@
 import {Component, Directive, ElementRef, Renderer} from 'angular2/core';
 import {RouteConfig, ROUTER_DIRECTIVES} from 'angular2/router';
-import {HTTP_PROVIDERS}    from 'angular2/http';
-
 import {AppProperties, AppPropertiesService} from './app-properties.service';
 
 @Directive({
@@ -42,7 +40,6 @@ export class About {
     XLarge
   ],
   providers: [
-    HTTP_PROVIDERS,
     AppPropertiesService
   ],
   styles: [`
@@ -53,8 +50,8 @@ export class About {
   template: `
   <div>
     <nav>
-      <a [routerLink]=" ['./Home'] ">Home</a>
-      <a [routerLink]=" ['./About'] ">About</a>
+      <a [routerLink]=" ['./Home', {}] ">Home</a>
+      <a [routerLink]=" ['./About', {}] ">About</a>
     </nav>
     <div>
       <span x-large>Hello, {{ name }}!</span>
@@ -97,5 +94,3 @@ export class App {
     });
   }
 }
-
-
diff --git a/src/client.ts b/src/client.ts
index 2cbb46d..71fcd8a 100644
--- a/src/client.ts
+++ b/src/client.ts
@@ -1,9 +1,11 @@
 // import {bootstrap} from 'angular2/platform/browser';
 import {bootstrap} from 'angular2-universal-preview';
 import {ROUTER_PROVIDERS} from 'angular2/router';
+import {HTTP_PROVIDERS} from 'angular2/http';
 
 import {App} from './app/app';
 
 bootstrap(App, [
-  ...ROUTER_PROVIDERS
+  ROUTER_PROVIDERS,
+  HTTP_PROVIDERS
 ]);

```

**Comment by manekinekko** [comment]
@gdi2290 this issue is also related to universal. feel free to close it :)
