### ISSUE TITLE
With nodeExternals whitelist, lazy modules not found anymore

### ISSUE THREAD

**Issue by peterpeterparker** [angular/universal-starter#425]
Hi,

I cloned the integration of `nodeExternals` in `webpack.server.js` in my project (like https://github.com/angular/universal-starter/blob/ff6c88159a9fb94aaba20b3744c48c2e303b7814/custom-webpack/webpack/webpack.server.js)  and as a result it seems that lazy modules aren't found anymore on the server side with this configuration.

If I remove back `nodeExternals` everything is working again respectively my lazy module is found.

Is there maybe still a mistake in the `whitelist` pattern?

Best regards

npm start error:

ERROR { Error: Uncaught (in promise): SyntaxError: Unexpected token export
/Users/me/Documents/projects/myproject/node_modules/@agm/core/index.js:2
export * from './directives';
^^^^^^

SyntaxError: Unexpected token export

npm run server error:

ERROR { Error: Uncaught (in promise): Error: Cannot find 'MyLazyViewModule' in './lazy/my-lazy-view.module'
Error: Cannot find 'MyLazyViewModule' in './lazy/my-lazy-view.module'
    at checkNotEmpty (/Users/me/projects/myproject/dist/server.js:5989:15)
    at /Users/me/projects/myproject/dist/server.js:5967:47
    at ZoneDelegate.invoke (/Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:391:26)
    at Object.onInvoke (/Users/me/projects/myproject/dist/server.js:4193:33)
    at ZoneDelegate.invoke (/Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:390:32)
    at Zone.run (/Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:141:43)
    at /Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:831:57
    at ZoneDelegate.invokeTask (/Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:424:31)
    at Object.onInvokeTask (/Users/me/projects/myproject/dist/server.js:4184:33)
    at ZoneDelegate.invokeTask (/Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:423:36)
    at resolvePromise (/Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:783:31)
    at resolvePromise (/Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:754:17)
    at /Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:831:17
    at ZoneDelegate.invokeTask (/Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:424:31)
    at Object.onInvokeTask (/Users/me/projects/myproject/dist/server.js:4184:33)
    at ZoneDelegate.invokeTask (/Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:423:36)
    at Zone.runTask (/Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:191:47)
    at drainMicroTaskQueue (/Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:595:35)
    at ZoneTask.invokeTask (/Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:502:21)
    at ZoneTask.invoke (/Users/me/projects/myproject/node_modules/zone.js/dist/zone-node.js:487:48)

The module's code:

    @NgModule({
      declarations: [MyLazyView, MyPipe],
      imports: [
        CommonModule,
        RouterModule.forChild([
          { path: ':id', component: MyLazyView, pathMatch: 'full'}
        ]),
        TranslateModule.forChild({
            loader: {
              provide: TranslateLoader,
              useFactory: exportTranslateStaticLoader,
              deps: [HttpClient]
            }
          }
        ),
        ComponentsModule,
        SliderModule,
        GoogleMapModule
      ],
      providers: [
        MyService
      ]
    })
    export class MyLazyViewModule {
    }

}

**Comment by peterpeterparker** [comment]
I'm dumb, I should extend the whitelisting (`whitelist: [/@angular/, /@ng/]`) with the libs I use

**Comment by gdi2290** [comment]
I added this to a gotcha. If the gotcha isn't clear can you make a PR to reword it for someone else
https://github.com/angular/universal-starter#universal-gotchas

**Comment by peterpeterparker** [comment]
@gdi2290 gotcha is pretty clear, I should I read it first, sorry for the issue

**Comment by gdi2290** [comment]
no problem 👍
