### ISSUE TITLE
Cannot start server after adding third party library like ngBootstrap

### ISSUE THREAD

**Issue by saravanan10393** [angular/universal-starter#428]
I add the 
```npm install --save @ng-bootstrap/ng-bootstrap``` 
package to this cli project and build the project with 
``` ng build --aot --app 1 ```
 then when try to start the server i get following error. 

```
/media/saravanan/studies/projects/universal-starter/cli/node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.js:1(function (exports, require, module, __filename, __dirname) { 
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy, } from '@angular/core';
 ^^^^^^SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.@ng-bootstrap/ng-bootstrap/alert/alert (/media/saravanan/studies/projects/universal-starter/cli/dist-server/main.bundle.js:1576:18)
```

It seems all the required dependencies  in project are not compiled in to common js module.

I am struggling with this for few hours , any help or suggestion is mostly welcome.

**Comment by dannyrevenant** [comment]
@saravanan10393 This issue is related to https://github.com/angular/angular-cli/issues/7200 . I wonder if the universal-starter maintainers have a solution for this in the mean time while we wait for the angular team to resolve the cli issue?

**Comment by saravanan10393** [comment]
@dannyrevenant thanks for mentioning out. It helps. :+1:

**Comment by MarkPieszak** [comment]
So besides other hackable ways of doing it, the easiest is basically setting up your `server.js` file in TypeScript, and having a webpack config to bundle it. In there you can set up `/.ts$/` files to use ts-loader, and make sure it grabs node_modules externals.

More information about this and most likely, updates to the CLI example, will be coming shortly to address these issues! 🍻 

Here's an example `server.ts` file

```typescript
import 'reflect-metadata';
import 'zone.js/dist/zone-node';
import { renderModuleFactory } from '@angular/platform-server';
import { enableProdMode } from '@angular/core';

import * as express from 'express';
import { join } from 'path';
import { readFileSync } from 'fs';

// Faster server renders w/ Prod mode (dev mode never needed)
enableProdMode();

const PORT = process.env.PORT || 4000;
const DIST_FOLDER = join(process.cwd(), 'dist');

// Express server
const app = express();

// Our index.html we'll use as our template
const template = readFileSync(join(DIST_FOLDER, 'index.html')).toString();

/* Here's we're using a webpack Alias to point to the file in the dist folder
 *   alias: {
 *     'main.server': path.join(__dirname, 'dist', 'server', 'main.bundle.js')
 *   }
 */
const { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require('main.server');

// Temporary (will be at: "@nguniversal/module-map-ngfactory-loader" soon)
const { provideModuleMap } = require('@markpieszak/module-map-ngfactory-loader');

app.engine('html', (_, options, callback) => {

  const universalOptions = {
    // Our index.html
    document: template,
    url: options.req.url,
    // DI so that we can get lazy-loading to work differently (since we need it to just instantly render it)
    extraProviders: [
      provideModuleMap(LAZY_MODULE_MAP)
    ]
  };

  renderModuleFactory(AppServerModuleNgFactory, universalOptions)
    .then(html => {
      callback(null, html);
    });

});

app.set('view engine', 'html');
app.set('views', 'src');

// Server static files from /browser
app.get('*.*', express.static(join(DIST_FOLDER, '/'), {
  maxAge: '1y'
}));

// ALl regular routes use the Universal engine
app.get('*', (req, res) => {
  console.log(`URL: ${req.url}`);
  // Set cache control headers
  res.set({
    'Cache-Control': 'public, max-age=31557600'
  });
  res.render('index', { req });
});

// Start up the Node server
app.listen(PORT, () => {
  console.log(`Node server listening on http://localhost:${PORT}`);
});
```

Example webpack config:
```typescript
const path = require('path');
const NormalModuleReplacementPlugin = require('webpack/lib/NormalModuleReplacementPlugin');

module.exports = {
  entry: {
    server: './server.ts'
  },
  resolve: {
    extensions: ['.ts', '.js'],
    alias: {
      'main.server': path.join(__dirname, 'dist', 'dist-server', 'main.bundle')
    }
  },
  target: 'node',
  externals: [
    /(node_modules|main\..*\.js)/,
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name].js'
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        loader: 'ts-loader',
      }
    ]
  },
  plugins: []
}

```
