### ISSUE TITLE
You must pass in a NgModule or NgModuleFactory to be bootstrapped

### ISSUE THREAD

**Issue by Scipionh** [angular/universal-starter#433]
I have just tried Angular Universal starting with your repo (cli version) I did customize it a bit by doing the following changes:

```
server.js

  var isOldIE = isIE(req.headers['user-agent']) && isIE(req.headers['user-agent']) !== 11 ? true : false
  if(isOldIE) {
      // Static
      res.render('index.html', {
          req: req,
          res: res
      });
  }
  else {
      // SPA
      res.sendFile('index.html', {root: __dirname});
  }
```
app.module.ts

```
@NgModule({
  imports: [
    CommonModule,
    HttpModule,
    RouterModule.forRoot([
  {
    path: '', redirectTo: '/comp', pathMatch: 'full'
  },
  {
    path: 'comp',
    loadChildren: 'app/comp/comp.module#CompModule'
  },
])
  ],
  declarations: [ AppComponent, ...],
  exports: [ AppComponent ]
})
export class AppModule {}
```

My comp module is basicaly a seed with only a main component display "foo"

If I try running it with a recent browser, I get the site working well (and I get the non-static version of the source).

Now If I do masquerade as IE10 by instance (changing my user-agent). I get the following error :
```
GET: /comp: 8.912ms
Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped
    at View.engine (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\@nguniversal\express-engine\src\main.js:34:23)
    at View.render (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\view.js:127:8)
    at tryRender (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\application.js:640:10)
    at EventEmitter.render (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\response.js:971:7)
    at app.get (C:\dev\workspace\neo\foyer-redbutton-front\ui\dist\server.js:50:11)
    at Layer.handle [as handle_request] (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\router\layer.js:95:5)
GET: /: 0.489ms
Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped
    at View.engine (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\@nguniversal\express-engine\src\main.js:34:23)
    at View.render (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\view.js:127:8)
    at tryRender (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\application.js:640:10)
    at EventEmitter.render (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\response.js:971:7)
    at app.get (C:\dev\workspace\neo\foyer-redbutton-front\ui\dist\server.js:50:11)
    at Layer.handle [as handle_request] (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\dev\workspace\neo\foyer-redbutton-front\ui\node_modules\express\lib\router\layer.js:95:5)

```

I used the following command :
`npm run serve:dynamic  -->  "serve:dynamic": "npm run build:dynamic && cd dist && node server"
`
I am not sure why. I tried doing something quite similar with the custom-webpack and didn't get any issue.

Any idea what am I doing wrong ?

**Comment by josemontiel** [comment]
@Scipionh what did you do to solve this issue?
