### ISSUE TITLE
npm start error " Error: Cannot find module 'hoek' "

### ISSUE THREAD

**Issue by munooo** [angular/universal-starter#46]
Error: Cannot find module 'hoek'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/manna/Project/e-munna/node_modules/angular2-universal-preview/node_modules/angular2-hapi-engine/dist/src/engine.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by manekinekko** [comment]
Could you clean and npm install again?

**Comment by munooo** [comment]
I run the start command  after clone repo and npm install command.

**Comment by manekinekko** [comment]
did you follow the installation process (in the right order): https://github.com/angular/universal-starter#installation

**Comment by gdi2290** [comment]
I updated universal to install hoek for hapi engine so you need to grab latest

**Comment by gdi2290** [comment]
closing for now since I included hoek as a dep
