### ISSUE TITLE
Use preboot with cli universal starter

### ISSUE THREAD

**Issue by CSchulz** [angular/universal-starter#466]
Added the modules like described in the readme of preboot but failing with following error:

> ERROR in ./node_modules/preboot/src/server/server-preboot.module.ts
> Module build failed: Error: Typescript emitted no output for /Users/ich/Documents/Daten/universal-starter/cli/node_modules/preboot/src/server/server-preboot.module.ts.
> You should not need to recompile .ts files in node_modules.
> Please contact the package author to advise them to use --declaration --outDir.
> More https://github.com/Microsoft/TypeScript/issues/12358
>     at successLoader (/Users/ich/Documents/Daten/universal-starter/cli/node_modules/ts-loader/dist/index.js:47:15)
>     at Object.loader (/Users/ich/Documents/Daten/universal-starter/cli/node_modules/ts-loader/dist/index.js:29:12)
>  @ ./dist/server/main.bundle.js 1:13835-13886
>  @ ./prerender.ts

Trying to run with `npm run build:static && npm run serve:static`

Example can be find here

https://github.com/CSchulz/universal-starter

**Comment by CSchulz** [comment]
Seems to be an issue with the webpack file https://github.com/angular/preboot/issues/39#issuecomment-335304249 .

The new preboot version (5.1.4) helps with browser module import in server module.
