### ISSUE TITLE
Getting an error in server.js file

### ISSUE THREAD

**Issue by khaled-ansary** [angular/universal-starter#470]
Hello, 
I am getting an error in `server.js` file.  I am not able to trace why I am getting this error.
I use the following command to build and run my project. 
`npm run build:dynamic && npm run serve:dynamic`

It build successfully but I getting the following error in `server.js` file

```
F:\Development\Angular Universal\universal-starter-master\dist\server.js:158774
    __metadata("design:paramtypes", [Event]),
                                     ^

ReferenceError: Event is not defined
    at Object.c (F:\Development\Angular Universal\universal-starter-master\dist\server.js:158774:38)
    at __webpack_require__ (F:\Development\Angular Universal\universal-starter-master\dist\server.js:20:30)
    at Object.defineProperty.value (F:\Development\Angular Universal\universal-starter-master\dist\server.js:147078:10)
    at __webpack_require__ (F:\Development\Angular Universal\universal-starter-master\dist\server.js:20:30)
    at Object.p4j/ (F:\Development\Angular Universal\universal-starter-master\dist\server.js:115664:448399)
    at n (F:\Development\Angular Universal\universal-starter-master\dist\server.js:115664:149)
    at Object.0OhI (F:\Development\Angular Universal\universal-starter-master\dist\server.js:115664:5120)
    at n (F:\Development\Angular Universal\universal-starter-master\dist\server.js:115664:149)
    at Object.GS2q (F:\Development\Angular Universal\universal-starter-master\dist\server.js:115664:155541)
    at n (F:\Development\Angular Universal\universal-starter-master\dist\server.js:115664:149)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-universal-demo@0.0.0 serve:dynamic: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-universal-demo@0.0.0 serve:dynamic script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ka\AppData\Roaming\npm-cache\_logs\2017-10-12T09_53_26_046Z-debug.log

```

**Comment by MarkPieszak** [comment]
This isn't from the base repo here right, is this your application put inside the example here?

It looks like a third party library causing issues, you'll have to start by going to that line in the server.js bundle and try to investigate which library is causing it. From there you'll have to use Webpack to swap that library out for a blank or mocked version for the server render.

Let us know!

**Comment by khaled-ansary** [comment]
Yes, I used the example  `universal-starter` repo and you are right that it is a third party library causing issue. I tried to run it using `gulp` and able to trace out the error. The error causing for `PrimeNg` library. I am getting now the following error ..

```
 ReferenceError: Event is not defined
    at Object.<anonymous> (F:\Development\Angular Universal\angular-universal-ma                                                                                                                                                                                      
ster\node_modules\primeng\src\app\components\tooltip\tooltip.ts:54:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\Development\Angular Universal\angular-universal-ma                                                                                                                                                                                               ster\node_modules\primeng\primeng.js:74:10)
    at Module._compile (module.js:570:32)
```
I have found the same issue in `PrimeNg` repo [https://github.com/primefaces/primeng/issues/2839](url) that can be solved by deleting  `tooltip, growl and datagrid` export from `primeng.js and primeng.d.ts`.

**Comment by MarkPieszak** [comment]
So you want to use `NormalModuleReplacementPlugin` to swap it out, I don't know the exact specifics of what you'd need for this one, but you could try first replacing it with a blank/empty file `empty.js` in the example below that's nothing more than

```typescript
module.exports = {};
```

But this might not work (and just throw other errors).

If worst comes to worst, you might need to copy/paste the prineng.js file, and just comment out or remove those functions/exports from it (maybe making them blank/empty {} or something).

I'm not sure if you'll have to touch the `.d.ts` files, it should work without doing that. You're just trying to get the server to Render and not throw that error above.

```typescript
const NormalModuleReplacementPlugin = require('webpack/lib/NormalModuleReplacementPlugin');

  // then in your plugins add... 
   plugins: [
    new NormalModuleReplacementPlugin(
      /prineng.js/,
      path.resolve(__dirname, 'src/server-mocks/empty.js')
      // or if you need to make some type of specific mock (copy/pasting) and editing
      path.resolve(__dirname, 'src/server-mocks/primeng.js')
    ),
```

**Comment by khaled-ansary** [comment]
Thanks the solution is working.

**Comment by christofferskog** [comment]
What exactly are `server-mocks`? I can't find it. I'm following https://github.com/angular/angular-cli/wiki/stories-universal-rendering rather than using this repo but I'm facing the same issue. I need some guidance.

**Comment by khaled-ansary** [comment]
Hi, you can create a folder in "src/server-mocks" or any other name that you have to mention in 
`NormalModuleReplacementPlugin`. 

For example, I was getting error for `tooltip` feature that was exported in `primeng.js`. So, I copied the `primeng.js` file into `server-mocks` and remove the `tooltip`  export code.
e.g. `//__export(require("./components/tooltip/tooltip"));` .  

So, you can copy a corrected `js` file into that folder and can mention those files into `NormalModuleReplacementPlugin` code. `NormalModuleReplacementPlugin ` replace the previous library files with new modified files.  

Usually, NodeJS gives these kind of error for DOM related code. So, you can also replace that code with corrected code and place that file into `server-mocks`  folder and also mention that in `NormalModuleReplacementPlugin ` using above code. For Example, I was created an issue for this here

https://github.com/angular/universal-starter/issues/472

**Comment by abhijithmannath** [comment]
@khaled-ansary I am facing a similar DOM related error, but I can't seem to get any sensible traceback so as to know which library is causing the issue. I am really new to webpack and angular, could you please explain how you used gulp to pinpoint the library.
