### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by khaled-ansary** [angular/universal-starter#472]
I am getting an error for `custom-event` library which may be use for `cross browser` support.  Angular universal does not support `DOM` related code. So how can I solve this problem? The error is following..
```
F:\Development\Angular Universal\angular-universal-master\node_modules\crossvent\node_modules\custom-event\index.js:24
'function' === typeof document.createEvent ? function CustomEvent (type, params) {
                      ^
ReferenceError: document is not defined
    at Object.<anonymous> (F:\Development\Angular Universal\angular-universal-master\node_modules\crossvent\node_modules\custom-event\index.js:24:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\Development\Angular Universal\angular-universal-master\node_modules\crossvent\src\crossvent.js:3:19)
```
The related question found in `https://stackoverflow.com/questions/45581696/angular-4-server-side-rendering-with-node-js-referenceerror-document-is-not-de` but still unsolved..

**Comment by MarkPieszak** [comment]
This will most likely be related & fixed with exactly how we did it in the other issue

https://github.com/angular/universal-starter/issues/470#issuecomment-336602788

This one could probably just be swapped out for an empty replacement.

**Comment by khaled-ansary** [comment]
Thanks. Its working. 
I copy the `custom-event` folder to `src/server-mocks/` and replace all `document` with `global.document` then apply the [#470 (comment)](url) solution.

**Comment by hesampour** [comment]
I have the same problem

**Comment by hiepxanh** [comment]
it should be note or fix, I facing the same problem

**Comment by IgorKurkov** [comment]
@khaled-ansary can you please describe how do you investigated which lib produce this error because I see that customEvent can be a part of angular directly.
