### ISSUE TITLE
Error trying to configure SCSS

### ISSUE THREAD

**Issue by Kayes-Islam** [angular/universal-starter#492]
Steps:

1. Rename styles.css file to styles.scss
2. Change angular-cli.json to set defaults.styleExt = scss.
3. `npm install` returns these warnings:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-gyp@^3.3.1 (node_modules\node-sass\node_modules\node-gyp):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unexpected end of JSON input while parsing near '...hasum":"e6c4199261986'
npm WARN sass-loader@6.0.6 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","a
rch":"x64"})
```
4. `npm run start` then gives the following errors:
```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader
/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Dev\Tests\universal-starter\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\Dev\Tests\universal-starter\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Dev\Tests\universal-starter\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Dev\Tests\universal-starter\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Dev\Tests\universal-starter\node_modules\loader-runner\lib\LoaderRunner.js:173:18
 @ ./src/styles.scss 4:14-187
 @ multi ./src/styles.scss
```

NOTE: It was working fine with universal starter seeder with Angular 4.

**Comment by Gorniv** [comment]
try `npm install -g node-sass`

**Comment by Kayes-Islam** [comment]
It's working now
