### ISSUE TITLE
btoa is not defined

### ISSUE THREAD

**Issue by Dinath** [angular/universal-starter#522]
I am using `"@angular/material": "^5.0.3"`, which I know seems not supported yet.

This **fatal error** seems caused by Material, but I do not know if it is true. How can I debug it? 
```
ReferenceError: btoa is not defined
    at new l (/home/alex/Projects/universal-starter/dist/server.js:127872:132461)
    at createClass (/home/alex/Projects/universal-starter/dist/server.js:12741:20)
    at _createProviderInstance (/home/alex/Projects/universal-starter/dist/server.js:12718:20)
    at createProviderInstance (/home/alex/Projects/universal-starter/dist/server.js:12559:12)
    at createViewNodes (/home/alex/Projects/universal-starter/dist/server.js:14034:53)
    at callViewAction (/home/alex/Projects/universal-starter/dist/server.js:14481:13)
    at execComponentViewsAction (/home/alex/Projects/universal-starter/dist/server.js:14390:13)
    at createViewNodes (/home/alex/Projects/universal-starter/dist/server.js:14075:5)
    at callViewAction (/home/alex/Projects/universal-starter/dist/server.js:14481:13)
    at execComponentViewsAction (/home/alex/Projects/universal-starter/dist/server.js:14390:13)
```

This one is not fatal, but I do not know which component is responsable.

```
ERROR { Error: Uncaught (in promise): ReferenceError: btoa is not defined
ReferenceError: btoa is not defined
    at new l (/home/alex/Projects/universal-starter/dist/server.js:127872:111378)
    at createClass (/home/alex/Projects/universal-starter/dist/server.js:12741:20)
    at _createProviderInstance (/home/alex/Projects/universal-starter/dist/server.js:12718:20)
    at createProviderInstance (/home/alex/Projects/universal-starter/dist/server.js:12559:12)
    at createViewNodes (/home/alex/Projects/universal-starter/dist/server.js:14034:53)
    at callViewAction (/home/alex/Projects/universal-starter/dist/server.js:14481:13)
    at execComponentViewsAction (/home/alex/Projects/universal-starter/dist/server.js:14390:13)
    at createViewNodes (/home/alex/Projects/universal-starter/dist/server.js:14075:5)
    at createRootView (/home/alex/Projects/universal-starter/dist/server.js:13936:5)
    at Object.createProdRootView [as createRootView] (/home/alex/Projects/universal-starter/dist/server.js:14629:12)
    at resolvePromise (/home/alex/Projects/universal-starter/dist/server.js:123520:31)
    at resolvePromise (/home/alex/Projects/universal-starter/dist/server.js:123484:17)
    at /home/alex/Projects/universal-starter/dist/server.js:123569:17
    at ZoneDelegate.invokeTask (/home/alex/Projects/universal-starter/dist/server.js:123120:31)
    at Object.onInvokeTask (/home/alex/Projects/universal-starter/dist/server.js:5015:33)
    at ZoneDelegate.invokeTask (/home/alex/Projects/universal-starter/dist/server.js:123119:36)
    at Zone.runTask (/home/alex/Projects/universal-starter/dist/server.js:122887:47)
    at drainMicroTaskQueue (/home/alex/Projects/universal-starter/dist/server.js:123293:35)
    at ZoneTask.invokeTask (/home/alex/Projects/universal-starter/dist/server.js:123198:21)
    at Server.ZoneTask.invoke (/home/alex/Projects/universal-starter/dist/server.js:123183:48)
  rejection: ReferenceError: btoa is not defined
    at new l (/home/alex/Projects/universal-starter/dist/server.js:127872:111378)
    at createClass (/home/alex/Projects/universal-starter/dist/server.js:12741:20)
    at _createProviderInstance (/home/alex/Projects/universal-starter/dist/server.js:12718:20)
    at createProviderInstance (/home/alex/Projects/universal-starter/dist/server.js:12559:12)
    at createViewNodes (/home/alex/Projects/universal-starter/dist/server.js:14034:53)
    at callViewAction (/home/alex/Projects/universal-starter/dist/server.js:14481:13)
    at execComponentViewsAction (/home/alex/Projects/universal-starter/dist/server.js:14390:13)
    at createViewNodes (/home/alex/Projects/universal-starter/dist/server.js:14075:5)
    at createRootView (/home/alex/Projects/universal-starter/dist/server.js:13936:5)
    at Object.createProdRootView [as createRootView] (/home/alex/Projects/universal-starter/dist/server.js:14629:12),
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value: ReferenceError: btoa is not defined
    at new l (/home/alex/Projects/universal-starter/dist/server.js:127872:111378)
    at createClass (/home/alex/Projects/universal-starter/dist/server.js:12741:20)
    at _createProviderInstance (/home/alex/Projects/universal-starter/dist/server.js:12718:20)
    at createProviderInstance (/home/alex/Projects/universal-starter/dist/server.js:12559:12)
    at createViewNodes (/home/alex/Projects/universal-starter/dist/server.js:14034:53)
    at callViewAction (/home/alex/Projects/universal-starter/dist/server.js:14481:13)
    at execComponentViewsAction (/home/alex/Projects/universal-starter/dist/server.js:14390:13)
    at createViewNodes (/home/alex/Projects/universal-starter/dist/server.js:14075:5)
    at createRootView (/home/alex/Projects/universal-starter/dist/server.js:13936:5)
    at Object.createProdRootView [as createRootView] (/home/alex/Projects/universal-starter/dist/server.js:14629:12) },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Zone],
        _name: 'angular',
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
```

**Comment by Dinath** [comment]
Closed because the error was caused by a service using http authentification.
