### ISSUE TITLE
Not possible to inject values with InjectionToken from node server to server bundle

### ISSUE THREAD

**Issue by sjogren** [angular/universal-starter#534]
I try to inject values from the `server.ts` into the built server bundle of the application like so:

**server.ts**
```ts
import { REST_URL } from './src/app/tokens';

app.engine('html', ngExpressEngine({
  bootstrap: AppServerModuleNgFactory,
  providers: [
    provideModuleMap(LAZY_MODULE_MAP),
    { provide: REST_URL , useValue: '/rest/' }
  ]
}));
```

**tokens.ts**
```ts
import { InjectionToken } from '@angular/core';

export const REST_URL = new InjectionToken('REST_URL');
```

**app.module.ts**
```ts
import { REST_URL } from './tokens';

export class AppModule {
  constructor(@Inject(REST_URL) private restUrl) {
    console.log('restUrl: ', restUrl);
  }
}
```

The `REST_URL` token is not recognized by the application injector since it is not the exact same reference to the token (it is defined in 2 places in the built `server.js`.

This generates the following error:
```
Error: StaticInjectorError(AppServerModule)[AppModule -> InjectionToken REST_URL]: 
  StaticInjectorError(Platform: core)[AppModule -> InjectionToken REST_URL]: 
    NullInjectorError: No provider for InjectionToken REST_URL!
    at _NullInjector.get (/Users/a.sjogren/Projects/Pierce/github/universal-starter/dist/server.js:2814:19)
    at resolveToken (/Users/a.sjogren/Projects/Pierce/github/universal-starter/dist/server.js:3112:24)
    at tryResolveToken (/Users/a.sjogren/Projects/Pierce/github/universal-starter/dist/server.js:3054:16)
    at StaticInjector.get (/Users/a.sjogren/Projects/Pierce/github/universal-starter/dist/server.js:2922:20)
    at resolveToken (/Users/a.sjogren/Projects/Pierce/github/universal-starter/dist/server.js:3112:24)
    at tryResolveToken (/Users/a.sjogren/Projects/Pierce/github/universal-starter/dist/server.js:3054:16)
    at StaticInjector.get (/Users/a.sjogren/Projects/Pierce/github/universal-starter/dist/server.js:2922:20)
    at resolveNgModuleDep (/Users/a.sjogren/Projects/Pierce/github/universal-starter/dist/server.js:12657:25)
    at _createClass (/Users/a.sjogren/Projects/Pierce/github/universal-starter/dist/server.js:12694:29)
    at _createProviderInstance$1 (/Users/a.sjogren/Projects/Pierce/github/universal-starter/dist/server.js:12668:26)
```

---

Reproduction of issue:

- Clone `https://github.com/sjogren/universal-starter`
- npm install
- npm run build:prerender
- npm run serve:ssr

Go to http://localhost:4000 in your browser to see the error.

**Comment by CaerusKaru** [comment]
Instead of using an `InjectionToken`, use a plain string value as follows:

`{provide: 'restUrl', useValue: '/rest'}`

Then inject as follows:

`@Inject('restUrl') private restUrl: string`

I can't say for certain, but I think the issue with the `InjectionToken` is that it gets compiled separately in each bundle, so you get a different reference than the one you want. With string values, it's a direct reference.

**Comment by dmitry-kostin** [comment]
@sjogren had a same issue today, did you solve this?
I was able to get it work in the following way:

server.ts
`{provide: 'HelloWorld', useFactory: () => 'helloWorld', deps: []}`

app.module.ts
```
constructor(@Inject(PLATFORM_ID) private platformId: Object, private injector: Injector) {
    if (isPlatformServer(this.platformId)) {
      console.log(this.injector.get<string>(<any>'HelloWorld'));
    }
 }
```

not sure this is nice method, but I didn't had a luck to do like you tried
