### ISSUE TITLE
Issue in parse5 library

### ISSUE THREAD

**Issue by m1uan** [angular/universal-starter#54]
After git clone && npm install ... npm start I get error message in console

```
...

> angular2-universal-starter@2.0.0 start /home/miuan/projects/universal-starter
> nodemon dist/server/bundle.js

[nodemon] 1.9.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/miuan/projects/universal-starter/dist/**/*
[nodemon] starting `node dist/server/bundle.js`
Listen on http://localhost:3000
/home/miuan/projects/universal-starter/node_modules/parse5/lib/tokenization/preprocessor.js:50
    this.lastCharPos = this.html.length - 1;
                                ^

TypeError: Cannot read property 'length' of null
    at Preprocessor.write (/home/miuan/projects/universal-starter/node_modules/parse5/lib/tokenization/preprocessor.js:50:33)
    at new module.exports (/home/miuan/projects/universal-starter/node_modules/parse5/lib/tokenization/preprocessor.js:29:10)
    at new module.exports (/home/miuan/projects/universal-starter/node_modules/parse5/lib/tokenization/tokenizer.js:148:25)
    at Parser._reset (/home/miuan/projects/universal-starter/node_modules/parse5/lib/tree_construction/parser.js:399:22)
    at Parser.parse (/home/miuan/projects/universal-starter/node_modules/parse5/lib/tree_construction/parser.js:361:10)
    at Object.parseDocument (/home/miuan/projects/universal-starter/node_modules/angular2-universal-preview/dist/node/platform/document.js:17:22)
    at Function.Bootloader.parseDocument (/home/miuan/projects/universal-starter/node_modules/angular2-universal-preview/dist/node/bootloader.js:32:72)
    at Bootloader.document (/home/miuan/projects/universal-starter/node_modules/angular2-universal-preview/dist/node/bootloader.js:38:31)
    at Bootloader.application (/home/miuan/projects/universal-starter/node_modules/angular2-universal-preview/dist/node/bootloader.js:47:24)
    at new Bootloader (/home/miuan/projects/universal-starter/node_modules/angular2-universal-preview/dist/node/bootloader.js:14:28)
[nodemon] app crashed - waiting for file changes before starting...
```
I also found command `npm run watch` doesn't turn on the server

**Comment by gdi2290** [comment]
@m1uan hi, thanks for opening an issue. The problem was on my end in one of the recent release. You can reinstall or update to latest for the fix. I'm going to close this but if you still have an issue feel free to reopen this one or create a new one, thanks.

**Comment by m1uan** [comment]
Thank you Patrick, it working awesome now !
very good job ;-)

2016-03-21 4:13 GMT+01:00 PatrickJS <notifications@github.com>:

> @m1uan <https://github.com/m1uan> hi, thanks for opening an issue. The
> problem was on my end in one of the recent release. You can reinstall or
> update to latest for the fix. I'm going to close this but if you still have
> an issue feel free to reopen this one or create a new one, thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/universal-starter/issues/54#issuecomment-199094585>
>



-- 
Best regards
        Milan Medlik
