### ISSUE TITLE
Cannot find module node-sass 

### ISSUE THREAD

**Issue by postmeback** [angular/universal-starter#547]
Whenever i am trying to run my project using angular-cli it gives the below error:

ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!.
/node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\arkap\AngularMyApp-master\node_modules\sass-
loader\lib\loader.js:3:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\Users\arkap\AngularMyApp-master\node_modules\loader-runner
\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\arkap\AngularMyApp-master\node_modules\l
oader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\arkap\AngularMyApp-master\node_modules\l
oader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\arkap\AngularMyApp-master\node_modules\loader-runner\lib\LoaderR
unner.js:173:18
ERROR in ./src/app/about/about.component.ts
Module not found: Error: Can't resolve './about.component.scss' in 'C:\Users\ark
ap\AngularMyApp-master\src\app\about'
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve './app.component.scss' in 'C:\Users\arkap
\AngularMyApp-master\src\app'
ERROR in ./src/app/home/home.component.ts
Module not found: Error: Can't resolve './home.component.scss' in 'C:\Users\arka
p\AngularMyApp-master\src\app\home'

webpack: Failed to compile.

Note : **I am behind a corporate proxy**

**Comment by postmeback** [comment]
Till now what i have done:

1. Deleted the node_modules folder and reinstalled it using **npm install** -- No Success
2. Tried to install node-sass package by using **npm install node-sass** -- No Success

**Comment by gtzinos** [comment]
Hello guys, probably you use nodejs linux package.

I faced some issues on my Linux environment and I removed it. I suggest you to use a package like nvm or y to manage versions.

**Comment by adeelibr** [comment]
```
$ rm package-lock.json
$ rm -rf node_modules
$ npm install
```
