### ISSUE TITLE
Error: No module factory available for dependency type: ContextElementDependency

### ISSUE THREAD

**Issue by netlander** [angular/universal-starter#583]
This error shows on a fresh install of 6.0.0 (`npm i && ng serve`):
```
Error: No module factory available for dependency type: ContextElementDependency
    at addDependency (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:407:12)
    at iterationOfArrayCallback (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:88:3)
    at addDependenciesBlock (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:423:5)
    at iterationOfArrayCallback (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:88:3)
    at addDependenciesBlock (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:426:5)
    at Compilation.processModuleDependencies (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:434:4)
    at afterBuild (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:556:15)
    at buildModule.err (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:600:11)
    at callback (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:358:35)
    at module.build.error (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:394:12)
    at resolveDependencies (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ContextModule.js:233:4)
    at ContextModule.result.resolveDependencies (C:\...\universal-starter\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:476:25)
    at ContextModule.build (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ContextModule.js:158:8)
    at Compilation.buildModule (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:362:10)
    at factory.create (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:583:14)
    at hooks.afterResolve.callAsync (C:\...\universal-starter\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ContextModuleFactory.js:150:16)
C:\...\universal-starter\node_modules\neo-async\async.js:14
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (C:\...\universal-starter\node_modules\neo-async\async.js:14:11)
    at C:\...\universal-starter\node_modules\neo-async\async.js:2805:7
    at process._tickCallback (internal/process/next_tick.js:150:11)
```

**Comment by Toxicable** [comment]
Thanks for reporting this. Looks like it's something to do with what module versions are installed.
What I mean by that is that if you install with `yarn` you wont see this issue since `yarn` is a bit better at handling modules and modules within modules.

So as a work around: use `yarn` instead.

I'll investigate whats going on here otherwise

**Comment by michaelmarshall** [comment]
using yarn to resolve this worked for me. thx @Toxicable

**Comment by netlander** [comment]
I'll give yarn a go once again. The last time I tried installing it on Win 10 it didn't go too well...

**Comment by michaelmarshall** [comment]
I used chocolatey to install yarn on win10pro. it went fine after a restart to get all the consoles to grab it.

**Comment by Ks89** [comment]
I suggest to commit also `package-lock.json` created with npm >= 5 to prevent these type of issues

**Comment by Toxicable** [comment]
So the issue here that we install webpack and @angular-devki/build-angular also installs webpack and due to the 2 copies there's conflicts.
The solution to this is to simply remove our version of webpack, then only the one version will be used.
Just ignore the peer dependency warning from webpack-cli when installing.

I still consider this a work around, we are working on a better solution but for now I am going to consider this resolved.

**Comment by netlander** [comment]
There only one Webpack Under node_module so the question is where is the other version and how to uninstall it to get this workaround to work?

**Comment by Toxicable** [comment]
I've have only tested this the cli v6, so unsure if it will work with v5
If you do `npm ls webpack` it should reveal the other webpack install under @angular-devkit/build-angular
Let me know if that's not the case

**Comment by netlander** [comment]
Yes it shows:
```
+-- @angular-devkit/build-angular@0.6.0
| `-- webpack@4.6.0
`-- webpack@4.8.1
```
Tried `npm uninstall webpack` and `npm uninstall webpack@4.8.1` both without much success. Also tried removing webpack dependency from package.json, that didn't work either.

----
**Which version to uninstall and what's the command that does it?**

**Comment by netlander** [comment]
The other thing is this issue shouldn't be closed as it describes a real bug in the 6.0.0 release of this repo, unless the developers are not interested in supporting **npm**, which is totally unacceptable.

**Comment by Toxicable** [comment]
You can get this working off a project that has `webpack` already installed by doing:
1.`npm ls webpack`
you should have the output
```
ng-universal-demo@0.0.0 /home/fabian/Documents/universal-starter
├─┬ @angular-devkit/build-angular@0.6.0
│ └── webpack@4.6.0
└── webpack@4.8.1
```
2. `npm uninstall webpack` then `npm ls webpack`
This will uninstall all copies of webpack so the output should be
```
fabian@fabian-desktop:~/Documents/universal-starter$ npm ls webpack
ng-universal-demo@0.0.0 /home/fabian/Documents/universal-starter
└── (empty)
```
3. Remove package-lock.json and node_modules then `npm install` and finally `npm ls webpack`
Which should then have the output
```
fabian@fabian-desktop:~/Documents/universal-starter$ npm ls webpack
ng-universal-demo@0.0.0 /home/fabian/Documents/universal-starter
└─┬ @angular-devkit/build-angular@0.6.0
  └── webpack@4.6.0
```

If successful then you can test it with `npm run build:ssr` if this succeeds then you're golden.
As an alternative you can simply edit your package.json to remove webpack, then remove your package-lock.json and node_modules then do a `npm install` and you should be good to go

----

I understand your frustration but I only have so much time in a day to maintain things around here.
I've investigated this issue and the solution i've provided is the best that's currently available.

**Comment by netlander** [comment]
@Toxicable thanks for your reply and I'm not all that frustrated. OK maybe a little bit due to this mass migration to `yarn` which implies that we should all drop everything and move away from `npm`. For some this is not an option. Will take a look at your solution later on. Thanks again.
