### ISSUE TITLE
Use environment variable on the server side.

### ISSUE THREAD

**Issue by gorkemyontem** [angular/universal-starter#587]
Hi,
I have two environment files. One for development and the other is for production. 
When I use `ng build --prod` and print out environment variables in app.component.ts, my browser console shows production variables. However, the terminal (server) is still showing the development variables. 
Why I need to use production variables on the server? Because I have different set of configuration on both environment. Ex:

Development
` 
ASSETS_URL: '/assets',  
API_URL: 'localhost'
`

Production
` 
ASSETS_URL: 'https://cdn.domain.com',  
API_URL: 'https://api.domain.com'
`

I have tried to run webpack with parameters. Such as,
`webpack -p` , `webpack --mode=production` or even I changed webpack.server.config.js files configuration, to `mode: "production"`. in all of these attempts I got the same error: 

`TypeError: StaticInjectorError[InjectionToken Application Initializer -> InjectionToken DocumentToken]:
  StaticInjectorError(Platform: core)[InjectionToken Application Initializer -> InjectionToken DocumentToken]:
    Right-hand side of 'instanceof' is not an object
    at bt (C:\Users\xxx\Desktop\universal-starter-master\dist\server.js:1623:68315)
    at gt (C:\Users\xxx\Desktop\universal-starter-master\dist\server.js:1623:68190)
    at ir (C:\Users\xxx\Desktop\universal-starter-master\dist\server.js:1623:90961)
    at We.insertToken (C:\Users\xxx\Desktop\universal-starter-master\dist\server.js:1623:67576)
    at C:\Users\xxx\Desktop\universal-starter-master\dist\server.js:1623:70854
    at Nt (C:\Users\xxx\Desktop\universal-starter-master\dist\server.js:1623:70869)
    at Ye (C:\Users\xxx\Desktop\universal-starter-master\dist\server.js:1623:65850)
    at Object.parse (C:\Users\xxx\Desktop\universal-starter-master\dist\server.js:1623:64836)
    at Object.t.createDocument (C:\Users\xxx\Desktop\universal-starter-master\dist\server.js:2098:76661)
    at Object.t.createWindow (C:\Users\xxx\Desktop\universal-starter-master\dist\server.js:2098:76765)`

Not sure If I am missing something or this is a bug.

**Comment by Toxicable** [comment]
duplicate of https://github.com/angular/universal-starter/issues/585

**Comment by gorkemyontem** [comment]
Thanks @Toxicable for the answer on #585
