### ISSUE TITLE
Deploy angular universal app on OVH VPS

### ISSUE THREAD

**Issue by KxL51** [angular/universal-starter#603]
I have develop a site with angular 5 which is live for now.

>FileZilla : https://www.noelshack.com/2018-23-2-1528188596-capture.png

I have put the dist folder content in the html folder and i run server.js with pm2.

But now I tried to deploy the version with angular universal for the SEO and it didn't work properly.
The site is host on a `OVH VPS`.

I got the dist repo like this : https://www.noelshack.com/2018-23-2-1528186340-capture.png.

Where did i need to put the server folder and prerender.js and server.js.

Any suggestions??

**Comment by hiepxanh** [comment]
your vps need run as express server and config your proxy to redirect to localhost:xxxx sir.

**Comment by KxL51** [comment]
Thanks for your answer. I have deploy the site but the connection with express doesn't seems to work.
you can have a look : http://www.jetestmessitetranquille.ovh
Go to textiles and what you want.

Got this error message : 

`<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Error: Failed to lookup view &quot;index&quot; in views directory &quot;/var/www/html/dist/browser&quot;
            <br> &nbsp; &nbsp;at Function.render (/var/www/html/server.js:117553:17)
            <br> &nbsp; &nbsp;at ServerResponse.render (/var/www/html/server.js:127772:7)
            <br> &nbsp; &nbsp;at /var/www/html/server.js:141:9
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/var/www/html/server.js:120002:5)
            <br> &nbsp; &nbsp;at next (/var/www/html/server.js:119750:13)
            <br> &nbsp; &nbsp;at Route.dispatch (/var/www/html/server.js:119725:3)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/var/www/html/server.js:120002:5)
            <br> &nbsp; &nbsp;at /var/www/html/server.js:119225:22
            <br> &nbsp; &nbsp;at param (/var/www/html/server.js:119298:14)
            <br> &nbsp; &nbsp;at param (/var/www/html/server.js:119309:14)
        </pre>
    </body>
</html>`
