### ISSUE TITLE
Build Application error

### ISSUE THREAD

**Issue by KxL51** [angular/universal-starter#605]
Hello,

When i launch "npm run build:prerender && npm run serve:prerender", it works fine until "cd dist && node prerender".
I got this error : 
`fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'D:\Cour\Serimaj\universal-starter-master\dist\browser\Textiles\tee-shirts'
    at Object.fs.mkdirSync (fs.js:885:18)
    at D:\Cour\Serimaj\universal-starter-master\dist\prerender.js:126418:14
    at Array.forEach (<anonymous>)
    at Object.defineProperty.value (D:\Cour\Serimaj\universal-starter-master\dist\prerender.js:126412:23)
    at __webpack_require__ (D:\Cour\Serimaj\universal-starter-master\dist\prerender.js:23:30)
    at D:\Cour\Serimaj\universal-starter-master\dist\prerender.js:75:18
    at Object.<anonymous> (D:\Cour\Serimaj\universal-starter-master\dist\prerender.js:78:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)`

Some helps needed please.

**Comment by alandroid** [comment]
Did you find a solution?

**Comment by KxL51** [comment]
Yes, I closed the issue. It was a mistake in static_path.ts
