### ISSUE TITLE
ERROR ReferenceError: document is not defined

### ISSUE THREAD

**Issue by JonasJW** [angular/universal-starter#623]
Hello,

I have followed [this](https://github.com/angular/angular-cli/wiki/stories-universal-rendering#serverts-root-project-level) guide  set up universal for my angular project.

Now when I run `node dist/server.js` it gives me the url to the localhost and as soon as I open it I get this Error:

`ERROR ReferenceError: document is not defined
    at new AppComponent (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:127183:9)
    at createClass (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:22920:20)
    at createDirectiveInstance (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:22805:20)
    at createViewNodes (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:24025:36)
    at createRootView (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:23939:5)
    at Object.createProdRootView [as createRootView] (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:24451:12)
    at ComponentFactory_.create (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:22285:29)
    at ComponentFactoryBoundToModule.create (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:16934:29)
    at ApplicationRef.bootstrap (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:18169:40)
    at /Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:17977:81
Unhandled Promise rejection: document is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: document is not defined
    at new AppComponent (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:127183:9)
    at createClass (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:22920:20)
    at createDirectiveInstance (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:22805:20)
    at createViewNodes (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:24025:36)
    at createRootView (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:23939:5)
    at Object.createProdRootView [as createRootView] (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:24451:12)
    at ComponentFactory_.create (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:22285:29)
    at ComponentFactoryBoundToModule.create (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:16934:29)
    at ApplicationRef.bootstrap (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:18169:40)
    at /Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:17977:81 ReferenceError: document is not defined
    at new AppComponent (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:127183:9)
    at createClass (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:22920:20)
    at createDirectiveInstance (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:22805:20)
    at createViewNodes (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:24025:36)
    at createRootView (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:23939:5)
    at Object.createProdRootView [as createRootView] (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:24451:12)
    at ComponentFactory_.create (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:22285:29)
    at ComponentFactoryBoundToModule.create (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTast/dist/server.js:16934:29)
    at ApplicationRef.bootstrap (/Users/jonas/Web Dev/ProjectR_FinishedSEO/ngTas`

I have searched a lot for a resolution but and I found that I can't use universal with 'document.'. I have actually used it but after I saw this I have commented out everything that uses `document` but that didn't solve my problem. Also I have tested universal with another project that actually uses `document` too but on this project it worked. So I assume my problem must be somewhere else. 

I searched a lot but I just couldn't find a solution. Here is my app.module.ts, maybe that gives someone a clue where my problem could be:

`@NgModule({

  declarations: [
    AppComponent,
    OfferComponent,
    OfferItemComponent,
    MenuComponent,
    CategrieItemComponent,
    DishItemComponent
  ],
  imports: [
    BrowserModule.withServerTransition({appId: 'my-app'}),
    NgbModule.forRoot(),
    NgsRevealModule.forRoot(),
    BrowserAnimationsModule,
    ScrollToModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`

Any Idea? Im grateful for every answer.

**Comment by abhijeet1403** [comment]
Not only you cannot use document in your project, But you cannot also use libraries which use document internally. So one of the imported modules is using document internally. So selectively import it.

**Comment by alandroid** [comment]
How do you selectively import?

**Comment by renilbabu03** [comment]
Put this code in your server.ts file

```
const domino = require("domino");
const fs = require("fs");
const path = require("path");
const templateA = fs
  .readFileSync(path.join("dist/sirved", "index.html"))
  .toString();
const win = domino.createWindow(templateA);
win.Object = Object;
win.Math = Math;

global["window"] = win;
global["document"] = win.document;
global["branch"] = null;
global["object"] = win.object;
```

**Comment by floodedcodeboy** [comment]
> const domino = require("domino"); const fs = require("fs"); const path = require("path"); const templateA = fs .readFileSync(path.join("dist/browser", "index.html")) .toString(); const win = domino.createWindow(templateA); win.Object = Object; win.Math = Math; global["window"] = win; global["document"] = win.document; global["branch"] = null; global["object"] = win.object;

This looks like a great solution. However is this really that simple? Angular describes that the PlatformBrowser be leveraged as a best practice. I'm very curious about what effects this has when you're Server Side Rendering a whole site.

**Comment by qubiack** [comment]
@floodedcodeboy I think that Angular present PlatformBrowser as the best solution because only in this case you get a full control over your code.
When you use 'domino' you doesn't get any error but your code doesn't work properly. Domino doesn't work exactly like browser so window object is not the same. 
Additionally, you can make unnecessary action in your node.js server, for example calculation of caret, focus etc. It always should happen only on browser.
In our project we doesn't use any window mock because it's not a solutions - it's like a temporary fix.
