### ISSUE TITLE
"@agm/core" Unexpected token import

### ISSUE THREAD

**Issue by Appjak34** [angular/universal-starter#631]
Error to load "@agm/core" 

/Users/appjak34/Documents/GrupoR28/node_modules/@agm/core/directives/marker.js:1

(function (exports, require, module, __filename, __dirname) { import { Directive, EventEmitter, ContentChildren, QueryList, Input, Output } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.@agm/core/directives/marker (/Users/appjak34/Documents/GrupoR28/dist/server/main.js:5588:18)

**Comment by uNmAnNeR** [comment]
Same issue here https://github.com/uNmAnNeR/imaskjs/issues/115
something wrong with build config?

**Comment by Gorniv** [comment]
you need use webpack for the build server.js like in https://github.com/Angular-RU/angular-universal-starter

**Comment by sioux-hockey** [comment]
I am experiencing the same issue and adding the webpack did not solve the problem.
