### ISSUE TITLE
@agm Unexpected token after removing wekpack

### ISSUE THREAD

**Issue by peterpeterparker** [angular/universal-starter#633]
[X] I want to report a bug or problem

**Describe the Bug**
I've got an Angular Universal project which I always sync with the last commits of this project (https://fluster.io)

After removing `webpack` as committed by @CaerusKaru in the following commits

https://github.com/angular/universal-starter/commit/7d59edfc8a9f6a644ae2cf10a79388defb0d2e61

https://github.com/angular/universal-starter/commit/d85b67038a18b0a2cc20e7eb8e1b9964b413ebea

I could still build (`npm run build:ssr`)  without any problems but I face the following error at runtime (`npm run serve`)

> node dist/server

> /Users/me/Documents/projects/myproject/node_modules/@agm/core/services/managers/marker-manager.js:1
> (function (exports, require, module, __filename, __dirname) { import { Injectable, NgZone } from '@angular/core';
>                                                                      ^
> 
> SyntaxError: Unexpected token {
>     at new Script (vm.js:74:7)
>     at createScript (vm.js:246:10)
>     at Object.runInThisContext (vm.js:298:10)
>     at Module._compile (internal/modules/cjs/loader.js:670:28)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
>     at Module.load (internal/modules/cjs/loader.js:612:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
>     at Module.require (internal/modules/cjs/loader.js:650:17)
>     at require (internal/modules/cjs/helpers.js:20:18)

**Related Code**

Same as the project itself but of course, as you could see in my subject and error, I use https://github.com/SebastianM/angular-google-maps to display a map

**Expected Behavior**
Being able to serve my project

**Workaround**
Reverting the remove of `webpack` and reusing `webpack.server.config.js` to compile solves the issue

**Info**
Angular 6.1.4
Agm 1.0.0-beta.3

**Issues to follow in agm**
https://github.com/SebastianM/angular-google-maps/issues/1052

**Comment by peterpeterparker** [comment]
I gonna close this issue I did open.

First of all I don't think that's an Angular Universal problem.

Then I solved my issue by removing the @agm library and replacing it by [web-google-maps](https://github.com/fluster/web-google-maps), a new Web Component to easily integrate Google Maps into any web applications which I created and published as an open source library
