### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by stellanhaglund** [angular/universal-starter#64]
I get this when I have built the app and try to run it

universal-starter/node_modules/angular2-universal-preview/node_modules/angular2-hapi-engine/node_modules/hoek/lib/index.js:5
const Crypto = require('crypto');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (universal-starter/node_modules/angular2-universal-preview/node_modules/angular2-hapi-engine/dist/src/engine.js:3:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by gdi2290** [comment]
thanks for opening an issue. You need node >=4.2.x for the module to work. I can recreate the function we're using so we won't run into this problem

**Comment by gdi2290** [comment]
I updated angular2-hapi-engine to use ts without `const` 0.7.1

**Comment by stellanhaglund** [comment]
Thanks!

Just a question that is not that related to this issue, but.
I'm completely new to angular 2, and I'm trying to understand what the capabilities universal adds.

I know it does rendering in the server side, but does that mean the entire application can be rendered on the server including realtime data and such?

**Comment by gdi2290** [comment]
realtime data and such can be rendered on the server so long as it's clear to the app that it's done (not having long running requests). I'm closing this now that the error is fixed. thanks for opening an issue
