### ISSUE TITLE
ERROR { Error: Uncaught (in promise): Error: no Promise impl found

### ISSUE THREAD

**Issue by qwertymuzaffar** [angular/universal-starter#648]
**Running node dist/server.js** 

ERROR { Error: Uncaught (in promise): Error: no Promise impl found
Error: no Promise impl found
    at Observable.forEach (C:\projects\sss-latest\dist\server.js:268:19)
    at Router.activateRoutes (C:\projects\sss-latest\dist\server.js:198881:14)
    at C:\projects\sss-latest\dist\server.js:198842:19
    at new ZoneAwarePromise (C:\projects\sss-latest\dist\server.js:171234:29)
    at Router.runNavigate (C:\projects\sss-latest\dist\server.js:198773:16)
    at C:\projects\sss-latest\dist\server.js:198728:30
    at ZoneDelegate.invoke (C:\projects\sss-latest\dist\server.js:170731:26)
    at Object.onInvoke (C:\projects\sss-latest\dist\server.js:10080:33)
    at ZoneDelegate.invoke (C:\projects\sss-latest\dist\server.js:170730:32)
    at Zone.run (C:\projects\sss-latest\dist\server.js:170481:43)
    at resolvePromise (C:\projects\sss-latest\dist\server.js:171157:31)
    at resolvePromise (C:\projects\sss-latest\dist\server.js:171114:17)
    at C:\projects\sss-latest\dist\server.js:171216:17
    at ZoneDelegate.invokeTask (C:\projects\sss-latest\dist\server.js:170764:31)
    at Object.onInvokeTask (C:\projects\sss-latest\dist\server.js:10071:33)
    at ZoneDelegate.invokeTask (C:\projects\sss-latest\dist\server.js:170763:36)
    at Zone.runTask (C:\projects\sss-latest\dist\server.js:170531:47)
    at drainMicroTaskQueue (C:\projects\sss-latest\dist\server.js:170938:35)
    at ZoneTask.invokeTask (C:\projects\sss-latest\dist\server.js:170843:21)
    at Server.ZoneTask.invoke (C:\projects\sss-latest\dist\server.js:170828:48)
  rejection: Error: no Promise impl found
    at Observable.forEach (C:\projects\sss-latest\dist\server.js:268:19)
    at Router.activateRoutes (C:\projects\sss-latest\dist\server.js:198881:14)
    at C:\projects\sss-latest\dist\server.js:198842:19
    at new ZoneAwarePromise (C:\projects\sss-latest\dist\server.js:171234:29)
    at Router.runNavigate (C:\projects\sss-latest\dist\server.js:198773:16)
    at C:\projects\sss-latest\dist\server.js:198728:30
    at ZoneDelegate.invoke (C:\projects\sss-latest\dist\server.js:170731:26)
    at Object.onInvoke (C:\projects\sss-latest\dist\server.js:10080:33)
    at ZoneDelegate.invoke (C:\projects\sss-latest\dist\server.js:170730:32)
    at Zone.run (C:\projects\sss-latest\dist\server.js:170481:43),
  promise: 
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value: Error: no Promise impl found
    at Observable.forEach (C:\projects\sss-latest\dist\server.js:268:19)
    at Router.activateRoutes (C:\projects\sss-latest\dist\server.js:198881:14)
    at C:\projects\sss-latest\dist\server.js:198842:19
    at new ZoneAwarePromise (C:\projects\sss-latest\dist\server.js:171234:29)
    at Router.runNavigate (C:\projects\sss-latest\dist\server.js:198773:16)
    at C:\projects\sss-latest\dist\server.js:198728:30
    at ZoneDelegate.invoke (C:\projects\sss-latest\dist\server.js:170731:26)
    at Object.onInvoke (C:\projects\sss-latest\dist\server.js:10080:33)
    at ZoneDelegate.invoke (C:\projects\sss-latest\dist\server.js:170730:32)
    at Zone.run (C:\projects\sss-latest\dist\server.js:170481:43) },
  zone: 
   Zone {
     _properties: { isAngularZone: true },
     _parent: 
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     _name: 'angular',
     _zoneDelegate: 
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [Object],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Object],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Object],
        _invokeZS: [Object],
        _invokeDlgt: [Object],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [Object],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [Object],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [Object],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [Object],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [Object],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task: 
   ZoneTask {
     _zone: 
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: 
      ZoneAwarePromise {
        __zone_symbol__state: 0,
        __zone_symbol__value: Error: no Promise impl found
    at Observable.forEach (C:\projects\sss-latest\dist\server.js:268:19)
    at Router.activateRoutes (C:\projects\sss-latest\dist\server.js:198881:14)
    at C:\projects\sss-latest\dist\server.js:198842:19
    at new ZoneAwarePromise (C:\projects\sss-latest\dist\server.js:171234:29)
    at Router.runNavigate (C:\projects\sss-latest\dist\server.js:198773:16)
    at C:\projects\sss-latest\dist\server.js:198728:30
    at ZoneDelegate.invoke (C:\projects\sss-latest\dist\server.js:170731:26)
    at Object.onInvoke (C:\projects\sss-latest\dist\server.js:10080:33)
    at ZoneDelegate.invoke (C:\projects\sss-latest\dist\server.js:170730:32)
    at Zone.run (C:\projects\sss-latest\dist\server.js:170481:43) },
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
Error: no Promise impl found
    at Observable.toPromise (C:\projects\sss-latest\dist\server.js:352:19)
    at C:\projects\sss-latest\dist\server.js:141024:14
    at ZoneDelegate.invoke (C:\projects\sss-latest\dist\server.js:170731:26)
    at Zone.run (C:\projects\sss-latest\dist\server.js:170481:43)
    at C:\projects\sss-latest\dist\server.js:171215:34
    at ZoneDelegate.invokeTask (C:\projects\sss-latest\dist\server.js:170764:31)
    at Zone.runTask (C:\projects\sss-latest\dist\server.js:170531:47)
    at drainMicroTaskQueue (C:\projects\sss-latest\dist\server.js:170938:35)
    at ZoneTask.invokeTask (C:\projects\sss-latest\dist\server.js:170843:21)
    at Server.ZoneTask.invoke (C:\projects\sss-latest\dist\server.js:170828:48)

**Comment by Toxicable** [comment]
What version of Nodejs are you running that on?
