### ISSUE TITLE
@Component template: does not find the template file

### ISSUE THREAD

**Issue by felipedrumond** [angular/universal-starter#86]
I'm trying to move the Home component to a pair of files (home.ts and home.html) like this:

`@Component({
    selector: 'home',
    template: require('home.html')
})`

Both home.ts and home.html are in src/app folder. I've tried even to use the absolute path of home.html, with no success.

run what gives me the following error:
ERROR in ./src/app/home.ts
Module not found: Error: Cannot resolve module 'home.html' in C:\Users\felip\Source\Repos\universal-starter\src\app
 @ ./src/app/home.ts 21:22-42

run gives me the following:

module.js:440
    throw err;
    ^

Error: Cannot find module 'home.html'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\felip\Source\Repos\universal-starter\dist\server\bundle.js:271:19)
    at __webpack_require__ (C:\Users\felip\Source\Repos\universal-starter\dist\server\bundle.js:20:30)
    at C:\Users\felip\Source\Repos\universal-starter\dist\server\bundle.js:210:24
    at Object.<anonymous> (C:\Users\felip\Source\Repos\universal-starter\dist\server\bundle.js:215:3)
    at __webpack_require__ (C:\Users\felip\Source\Repos\universal-starter\dist\server\bundle.js:20:30)
    at Object.c (C:\Users\felip\Source\Repos\universal-starter\dist\server\bundle.js:121:15)

What do I need to successfully separate my controllers using a TS and HTML file?

**Comment by bigbassroller** [comment]
try  ``` templateUrl: 'src/app/home.html'```

**Comment by felipedrumond** [comment]
Thank you Michael! It really solved the issue!

**Comment by Bhushan001** [comment]
@felipedrumond if its solved then please close this issue.

**Comment by gdi2290** [comment]
you need ./home.html
